%% Submissions for peer-review must enable line-numbering
%% using the lineno option in the \documentclass command.
%%
%% Preprints and camera-ready submissions do not need
%% line numbers, and should have this option removed.
%%
%% Please note that the line numbering option requires
%% version 1.1 or newer of the wlpeerj.cls file, and
%% the corresponding author info requires v1.2

\documentclass[fleqn,10pt,lineno]{wlpeerj} % for journal submissions

% ZNK -- Adding headers for pandoc

\setlength{\emergencystretch}{3em}
\usepackage[unicode=true]{hyperref}

% Pandoc syntax highlighting
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}

% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% From pandoc table feature
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}

% Pandoc citation processing
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[L]{Revell, L. J. (2023)}
\fancyhead[C]{}
\fancyhead[R]{phytools 2.0}


\title{phytools 2.0: An updated R ecosystem for phylogenetic comparative methods (and other things)}

\author[1, 2]{Liam J. Revell}

\corrauthor[1, 2]{Liam J. Revell}{\href{mailto:liam.revell@umb.edu}{\nolinkurl{liam.revell@umb.edu}}}

\affil[1]{Department of Biology, University of Massachusetts Boston, Boston, MA, USA}
\affil[2]{Facultad de Ciencias, Universidad Católica de la Santísima Concepción, Concepción, Chile}


%
% \author[1]{First Author}
% \author[2]{Second Author}
% \affil[1]{Address of first author}
% \affil[2]{Address of second author}
% \corrauthor[1]{First Author}{f.author@email.com}

% 

\begin{abstract}
Phylogenetic comparative methods comprise the general endeavor of using an estimated phylogenetic tree (or set of trees) to make secondary inferences: about trait evolution, diversification dynamics, biogeography, community ecology, and a wide range of other phenomena or processes. Over the past ten years or so, the \emph{phytools} R package (Revell 2012) has grown to become one of the most important research tools for phylogenetic comparative analysis. \emph{phytools} is a diverse contributed R library now consisting of hundreds of different functions covering a variety of methods and purposes in phylogenetic biology. As of the time of writing, \emph{phytools} included functionality for fitting models of trait evolution, for reconstructing ancestral states, for studying diversification on trees, and for visualizing phylogenies, comparative data, and fitted models, as well numerous other tasks related to phylogenetic biology. Here, I describe some significant features of and recent updates to \emph{phytools}, while also illustrating several popular workflows of the \emph{phytools} computational software.
% Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text. Dummy abstract text.
\end{abstract}

\begin{document}



\flushbottom
\maketitle
\thispagestyle{empty}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Phylogenetic trees are the directed graphs used to represent historical relationships among a set of operational taxa that are thought to have arisen via a process of descent with modification and branching (Felsenstein 2004; Harmon 2019). Operational taxa in a reconstructed phylogenetic tree might be gene copies, paralogous and orthologous members of a gene family, viral sequences, whole genomes, human cultural groups, or biological species (Yang 2014). According to its broadest definition, the phylogenetic comparative method corresponds to the general activity of using a known or (most often) estimated phylogenetic tree to learn something \emph{else} (apart from the relationships indicated by the tree) about the evolutionary process or past, the contemporary ecology, the biogeographic history, or the origins via diversification, of the particular taxa of our estimated tree (Harvey and Pagel 1991; Felsenstein 2004; Nunn 2011; Harmon 2019; Revell and Harmon 2022).

Modern phylogenetic comparative methods are not new. Perhaps the most important article in the development of the phylogenetic approach to comparative biology (Felsenstein 1985) was first authored nearly 40 years ago, and was even the subject of a recent retrospective (Huey et al. 2019). Nonetheless, it's fair to say that phylogenetic comparative methods have seen a relatively impressive expansion and diversification over the past two decades (e.g., Butler and King 2004; Felsenstein 2005; O'Meara et al. 2006; Maddison et al. 2007; Hohenlohe and Arnold 2008; Revell and Collar 2009; Morlon et al. 2010; Stadler 2011; Etienne and Haegeman 2012; Goldberg and Igić 2012; Beaulieu et al. 2013; Rabosky 2014; Uyeda and Harmon 2014; Beaulieu and O'Meara 2016; Revell 2021, and many others; reviewed in Garamszegi 2014; Harmon 2019; Revell and Harmon 2022). This has included the development of new approaches for studying the generating processes of trees (that is, speciation and extinction), the relationship between phenotypic traits and species diversification, and a range of techniques for investigating heterogeneity in the evolutionary process across the branches and clades of the tree of life (Harmon 2019; Revell and Harmon 2022).

Phylogenetic comparative methods have also begun to be applied extensively outside of their traditional domain of evolutionary research. In particular, phylogenies and the comparative method have made recent appearances in studies on infectious disease epidemiology, virology, cancer biology, sociolinguistics, biological anthropology, molecular genomics, and community ecology, among other disciplines (e.g., Moura et al. 2016; Baele et al. 2018; Bentz et al. 2018; Beale et al. 2019; Bushman et al. 2019; Sánchez-Busó et al. 2019; Valles-Colomer et al. 2019; Freitas et al. 2020; Jezovit et al. 2020; Blinkhorn and Grove 2021; McLaughlin et al. 2022; Pepke and Eisenberg 2022; Pozzi et al. 2022; Compton et al. 2023; Mifsud et al. 2023; Van Borm et al. 2023, and many others).

The scientific computing environment R (R Core Team 2022) is widely-used in biological research. One of the major advantages that R provides is that it empowers computational scientists and independent developers to build functionality on top of the basic R platform. This functionality often takes the form of what are called contributed R packages: libraries of related functions built by individuals or research collaboratives not part of the core R development team. The growth of importance of R in phylogenetic biology stems entirely from contributed R package. Among these, the most important core function libraries are \emph{ape} (Paradis et al. 2004; Popescu et al. 2012; Paradis and Schliep 2019), \emph{geiger} (Harmon et al. 2008; Pennell et al. 2014), \emph{phangorn} (Schliep 2011), and my package, \emph{phytools} (Revell 2012).

\emph{phytools} is an R function library dedicated primarily to phylogenetic comparative analysis, but also including approaches and methodologies in a range of other domains of phylogenetic biology -- not restricted to, but especially, visualization. The original article describing \emph{phytools} is now more than 10 years old, and though I recently published a more comprehensive book on the subject of phylogenetic comparative methods in the R environment (Revell and Harmon 2022), I nonetheless felt that it was time to provide a briefer (although this article is by no means brief) update of \emph{phytools} specifically -- for the primary scientific literature. This is the main purpose of the current article.

The \emph{phytools} library has now grown to be very large -- consisting of hundreds of functions, a documentation manual that's over 200 pages in length, and tens of thousands of lines of computer code. As such, I thought it would be most useful to compactly summarize some of the functionality of the \emph{phytools} R package in a few different areas, but each time provide a small set of more detailed example analytical workflows for the current ``2.0'' version of the \emph{phytools} package.

\hypertarget{overview}{%
\section{Overview}\label{overview}}

The \emph{phytools} R package contains functionality in a diversity of different research areas of phylogenetics and phylogenetic biology. Rather than attempt a comprehensive survey of this functionality here, what I've elected to do instead is briefly review a smaller number of methodological areas, and then illustrate each of these with multiple analysis workflows -- including the corresponding R code that can be used to reproduce the analysis and results presented.

My hope is that this article will serve as more than the typical software note placeholder for \emph{phytools}, and may instead aid R phylogenetic users, both new and old, to be inspired to apply some of the methodologies illustrated herein to their own questions and data.

\hypertarget{installing-and-loading-phytools}{%
\section{\texorpdfstring{Installing and loading \emph{phytools}}{Installing and loading phytools}}\label{installing-and-loading-phytools}}

This article assumes that readers already have some familiarity with the R computing environment, and have previously installed contributed R packages. Nonetheless, to get started using \emph{phytools}, the easiest way to install the package locally is by using the R base function called \texttt{install.packages}, which will download and install \emph{phytools} from its CRAN page. (CRAN is an acronym for Comprehensive R Archive Network: a network of mirror repositories used both to archive and distribute R and contributed R packages.)

After opening a new interactive R session, this can be done as follows.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"phytools"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Readers undertaking phylogenetic analysis in the R environment for the first time will note that when we ask R to install \emph{phytools}, several other R packages are also downloaded and installed automatically. These are packages upon which \emph{phytools} depends -- meaning that \emph{phytools} uses one or multiple functions exported by each of these packages in its own internal R code. More will be said later about the dependency relationship between \emph{phytools} and other packages of the R and R phylogenetic ecosystems.

Having installed \emph{phytools}, if we'd like to proceed and use it in an interactive R session, we'd normally load it. (Loading an R package simply makes the names of the functions of that package visible and available in our current R session.) This can be done using the base R function \texttt{library}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(phytools)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ape
\end{verbatim}

\begin{verbatim}
## Loading required package: maps
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{packageVersion}\NormalTok{(}\StringTok{"phytools"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] '1.5.12'
\end{verbatim}

(I expect that this version number with be updated to \texttt{phytools\ 2.0} by the time this article is published!) The \emph{phytools} package is now loaded.

\hypertarget{discrete-characters}{%
\section{Discrete characters}\label{discrete-characters}}

The \emph{phytools} R library now contains a wide range of different methods and models for the analysis of \emph{discrete character evolution} on trees. For example, \emph{phytools} can be used to fit and plot an extended M\emph{k} model (\emph{phytools} function \texttt{fitMk}, Lewis 2001; Harmon 2019), it can fit Pagel's correlational binary trait evolution model (\texttt{fitPagel}, Pagel 1994), it can be used to perform stochastic character mapping and reconstruct ancestral states under the M\emph{k} and threshold models (\texttt{make.simmap}, \texttt{simmap}, \texttt{ancThresh}, and \texttt{rerootingMethod}, Huelsenbeck et al. 2003; Felsenstein 2005, 2012; Revell 2014), it can fit a polymorphic trait evolution model (\texttt{fitpolyMk}, Revell and Harmon 2022), it can fit a hidden-rates model (\texttt{fitHRM}, Beaulieu et al. 2013), it can compare the rate of discrete character evolution between clades and trees (\texttt{fitmultiMk} and \texttt{ratebytree}, Revell et al. 2018; Revell and Harmon 2022), and it can simulate discrete character data under multiple models (e.g., \texttt{sim.Mk}, \texttt{sim.history}, \texttt{sim.multiMk}).

In this section, I'll illustrate the use of just a few of the different discrete character methods that have been implemented in the \emph{phytools} software.

\hypertarget{stochastic-character-mapping}{%
\subsection{Stochastic character mapping}\label{stochastic-character-mapping}}

Perhaps the most important and widely-used discrete character method of \emph{phytools} is a technique referred to as ``stochastic character mapping'' (Huelsenbeck et al. 2003). Stochastic character mapping is a method in which we randomly sample discrete character histories (``stochastic maps'') of our trait on the tree under a specified model.

This can be undertaken in more than one way. An example of a stochastic character mapping analysis could be to first fit (e.g., using Maximum Likelihood) the character transition model (a variant of the M\emph{k} discrete character evolution model of Lewis 2001; also see, Harmon 2019; Revell and Harmon 2022), and then proceed to randomly sample a set of 1,000 (perhaps) random character histories under this model that are consistent with the phenotypic trait observations that we have for the terminal taxa of our tree.

(Other workflows are also popular and possible to undertake within R. For instance, rather than use a single, fixed model of character evolution that's been optimized using Maximum Likelihood, one might instead sample parameters of the evolutionary process from their joint posterior probability distribution using Bayesian MCMC. See Revell and Harmon 2022 for more details.)

To illustrate this approach here, I'll use a discretely-valued, ecological trait for a small phylogeny of centrarchid fishes from Revell and Collar (2009). Since the trait (which we'll refer to as ``feeding mode'') is binary, meaning that it only takes two levels, there are a total of four possible discrete character (extended M\emph{k}, see Harmon 2019) models: equal back-and-forth transitions between the two character values; different rates; and then the two different irreversible trait evolution models.

\emph{phytools} now allows us to fit each of these four different models, compare them, and pass the model weights and fitted models directly to our stochastic mapping function. Our function (called \texttt{simmap}) will then proceed to automatically sample stochastic character histories with probabilities that are proportional to each model weight. (Experience \emph{phytools} users may figure out that \texttt{simmap} is just a sophisticated wrapper function of \texttt{make.simmap} -- the traditional method used for undertaking stochastic character mapping in \emph{phytools}.)

For this example, and all subsequent examples of the article, our data have been packaged with the \emph{phytools} library -- so we can easily load them in an interactive R session using the base R function \texttt{data} as follows.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(sunfish.tree)}
\FunctionTok{data}\NormalTok{(sunfish.data)}
\end{Highlighting}
\end{Shaded}

For our M\emph{k} model-fitter (which here will be the \emph{phytools} function \texttt{fitMk}), and for the other discrete character methods of the \emph{phytools} R package, our input phenotypic trait data will typically takes the form of a character or factor vector. Personally, I prefer to use factors, because in that case we can more easily access the levels assumed by the character through a call of the base R function \texttt{levels}.

(In this example our input data consists of a data frame in which the \texttt{feeding.mode} column is already coded as a factor. In general, however, had we read this data from an input text file in, for example, comma-separated-value format, R would've created a character, rather than factor, formatted column by default. To adjust this we can set the argument \texttt{stringsAsFactors=TRUE} in our file-reading function, which, in that case, might be the base R function \texttt{read.csv}.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{feeding\_mode}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(sunfish.data}\SpecialCharTok{$}\NormalTok{feeding.mode,}
  \FunctionTok{rownames}\NormalTok{(sunfish.data))}
\FunctionTok{levels}\NormalTok{(feeding\_mode)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "non"  "pisc"
\end{verbatim}

Here we see that our factor vector has two levels: \texttt{"non"} and \texttt{"pisc"}. These two character levels refer to non-piscivorous and piscivorous fish species in this group. Since R factors have no particular character limit on their levels, let's update our data to use these more descriptive names: once again using the function \texttt{levels}.

(\texttt{levels} is an odd R method in that it can serve both as an \emph{extractor} function, that pulls out the levels of a factor -- as well as acting as an assignment or \emph{replacement} function, in which the levels of the factor are updated. When we adjust our factor levels for \texttt{feeding\_mode}, we're using \texttt{levels} in this latter fashion.)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(feeding\_mode)}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(}\StringTok{"non{-}piscivorous"}\NormalTok{,}
  \StringTok{"piscivorous"}\NormalTok{)}
\FunctionTok{levels}\NormalTok{(feeding\_mode)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "non-piscivorous" "piscivorous"
\end{verbatim}

Now we're ready to proceed and fit our models. To do so, I'll use the \emph{phytools} function \texttt{fitMk} and fit a total of four models, as previously indicated: \texttt{"ER"}, the equal rates model; \texttt{"ARD"}, the all-rates-different model; and, lastly, the two different irreversible models -- one in which non-piscivory can evolve to piscivory, but not the reverse; and a second in which precisely the opposite is true.

For our two irreversible models, we'll tell \texttt{fitMk} how to construct the model by creating and supplying what I'll refer to as a ``design matrix'' for each model that we want to fit. This design matrix should be of dimensions \emph{k} \(\times\) \emph{k}, for \emph{k} levels of the trait, with integer values in the positions of the matrix corresponding to allowed transitions, and zeros elsewhere. (We use different non-zero integer value for each rate that we want to permit to assume a different value in our fitted model.)

Since our \emph{k} = 2, this is very easy; however, the same principle would apply to any value of \emph{k} (see Revell and Harmon 2022 for more examples).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ER.model}\OtherTok{\textless{}{-}}\FunctionTok{fitMk}\NormalTok{(sunfish.tree,feeding\_mode,}
  \AttributeTok{model=}\StringTok{"ER"}\NormalTok{)}
\NormalTok{ARD.model}\OtherTok{\textless{}{-}}\FunctionTok{fitMk}\NormalTok{(sunfish.tree,feeding\_mode,}
  \AttributeTok{model=}\StringTok{"ARD"}\NormalTok{)}
\NormalTok{Irr1.model}\OtherTok{\textless{}{-}}\FunctionTok{fitMk}\NormalTok{(sunfish.tree,feeding\_mode,}
  \AttributeTok{model=}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{),}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{))}
\NormalTok{Irr2.model}\OtherTok{\textless{}{-}}\FunctionTok{fitMk}\NormalTok{(sunfish.tree,feeding\_mode,}
  \AttributeTok{model=}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{),}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Having fit our four models, we can also compare them to see which is best-supported by our data. To do so, I'll use a generic \texttt{anova} function call as follows. \texttt{anova} will print the results of our model comparison; however, it's important that we also assign the value returned by \texttt{anova} to a new object. In my example, I'll call this object \texttt{sunfish.aov}, but the name is arbitrary.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sunfish.aov}\OtherTok{\textless{}{-}}\FunctionTok{anova}\NormalTok{(ER.model,Irr1.model,}
\NormalTok{  Irr2.model,ARD.model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               log(L) d.f.      AIC    weight
## ER.model   -13.07453    1 28.14906 0.3486479
## Irr1.model -12.98820    1 27.97640 0.3800846
## Irr2.model -14.20032    1 30.40064 0.1130998
## ARD.model  -12.86494    2 29.72987 0.1581677
\end{verbatim}

This table shows each of our fitted model names, their log-likelihoods, the number of parameters estimated, a value of the Akaike Information Criterion (AIC), and the Akaike model weights. Smaller values of AIC indicate better support for the corresponding model -- taking into account its parameter complexity. Model weights can be interpreted as the ``weight of evidence'' favoring each of our four trait evolution hypotheses.

Based on this analysis, we might conclude that the first irreversible model (\texttt{Irr1.model}), in which non-piscivory can evolve to piscivory, but not the reverse, is best supported; however, we have a very similar weight of evidence favoring the equal-rates model (\texttt{ER.model}).

With the result of our \texttt{anova} call in hand (as the \texttt{sunfish.aov} object), we're ready to pass it on directly to \emph{phytools}' new generic \texttt{simmap} method. By design, doing so will tell \texttt{simmap} to generate stochastic character maps under each of our four models with relative frequencies that are equal to the weight of evidence supporting of each model. (If we preferred, we could've generated stochastic character maps for just the best-supported of our four models. Using the \texttt{simmap} generic method, this would be done either by supplying our \texttt{anova} result and setting the argument \texttt{weighted=FALSE} -- or simply by passing our favored M\emph{k} model directly to the function!)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sunfish.simmap}\OtherTok{\textless{}{-}}\FunctionTok{simmap}\NormalTok{(sunfish.aov,}\AttributeTok{nsim=}\DecValTok{1000}\NormalTok{)}
\NormalTok{sunfish.simmap}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 1000 phylogenetic trees with mapped discrete characters
\end{verbatim}

In spite of the significant number of stochastic simulations involved, this analysis should run fairly quickly (obviously, depending on the speed of our computer). In part this is because we saved computation time by circumventing the need to re-estimate our M\emph{k} transition matrix, \textbf{Q}, separately for each sampled model. An additional advantage of this approach is that it's also allowed us to (partly) account for variation in our modeled process of evolution that's due to uncertainty in model selection.

Figure \ref{fig:simmap-trees} shows a set of six, randomly chosen stochastic character histories for our trait (feeding mode) on our input tree. Readers should see that each of these are consistent with our observed value of the binary trait at the tips of the tree, but that each differs one from the other in the specific hypothesis of trait evolution that it represents.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(viridisLite}\SpecialCharTok{::}\FunctionTok{viridis}\NormalTok{(}\AttributeTok{n=}\DecValTok{2}\NormalTok{),}
  \FunctionTok{levels}\NormalTok{(feeding\_mode))}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{sample}\NormalTok{(sunfish.simmap,}\DecValTok{6}\NormalTok{),}\AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}
  \AttributeTok{fsize=}\FloatTok{0.6}\NormalTok{,}\AttributeTok{colors=}\NormalTok{cols,}\AttributeTok{offset=}\FloatTok{0.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/simmap-trees-1} \caption{Six randomly chosen stochastic character maps of feeding mode (non-piscivorous, in dark blue, vs. piscivorous) on a phylogeny of 28 centrarchid fish species. Stochastic character mapping involves randomly sampling character histories that are consistent with our tip data in proportion to their probability under a model. In this case, histories were sampled under the set of four alternative M\textit{k} models of a binary trait, with relative frequencies proportional to the weight of evidence supporting each model. The tree and data are modified from Revell and Collar (2009). See main text for additional details.}\label{fig:simmap-trees}
\end{figure}

To create my color palette for plotting I used another contributed R package that we haven't seen yet called \emph{viridisLite} by Garnier et al. (2022). To replicate Figure \ref{fig:simmap-trees} exactly, users should first install \emph{viridisLite} from CRAN by running \texttt{install.packages("viridisLite")} -- but they do not need to load it. (Calling the contributed package function using the double colon syntax, \texttt{::}, takes care of that -- i.e., \texttt{viridisLite::viridis}.)

Although Figure \ref{fig:simmap-trees} already gives us a general sense of the uncertainty of our ancestral character history on the tree for our trait, most commonly we don't want to simply graph a subset (or all) of our stochastically mapped trees. Typically, instead, we'd first summarize our stochastic character maps (in multiple ways), and then proceed to plot or analyze these summarized findings.

Perhaps most often, \emph{phytools} users undertaking stochastic character mapping will compute the posterior probabilities of each value of the character trait at each internal node of the tree. In \emph{phytools}, these values can be obtained using the generic \texttt{summary} method for our object class, which is then easily plotted as follows.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{summary}\NormalTok{(sunfish.simmap),}\AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}
  \AttributeTok{fsize=}\FloatTok{0.7}\NormalTok{,}\AttributeTok{colors=}\NormalTok{cols,}\AttributeTok{cex=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.3}\NormalTok{))}
\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{,}\FunctionTok{levels}\NormalTok{(feeding\_mode),}\AttributeTok{pch=}\DecValTok{21}\NormalTok{,}
  \AttributeTok{pt.cex=}\FloatTok{1.5}\NormalTok{,}\AttributeTok{pt.bg=}\NormalTok{cols,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/posterior-probs-1} \caption{Posterior probabilities at each ancestral node of the centrarchid tree of Figure 1 from stochastic character mapping using model weights to sample across four different extended M\textit{k} trait evolution models. See main text for more details.}\label{fig:posterior-probs}
\end{figure}

A correct interpretation of the graph of Figure \ref{fig:posterior-probs} is that it shows the observed discrete character states (at the tips of the tree) and the posterior probabilities from stochastic mapping that each internal node is in each state -- all while integrating over our four different transition models in proportion to the weight of evidence in support of each model!

In addition to node probabilities, \emph{phytools} users undertaking a stochastic character mapping analysis are often interested in the number of changes of each type that are implied by the evolutionary process and our data. The procedure of stochastic mapping samples full character histories (not just states or probabilities at nodes), and can thus be deployed to produce estimates of the posterior probability distribution of the character changes of each type on specific edges, in specific clades, or on the entire tree, conditioning on our sampled model or models.

To obtain these distributions, we'll first call the generic method \texttt{density} which (when given an object from stochastic mapping) computes the relative frequency distribution of changes of each type over the whole tree. We can then graph these distributions (remember, our character is binary, so there are only two types of character state change: non-piscivorous \(\rightarrow\) piscivorous, and the reverse) using a different generic \texttt{plot} method, as follows.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sunfish.density}\OtherTok{\textless{}{-}}\FunctionTok{density}\NormalTok{(sunfish.simmap)}
\NormalTok{sunfish.density}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Distribution of changes from stochastic mapping:
##  non-piscivorous->piscivorous        piscivorous->non-piscivorous
##  Min.   :0   Min.   :0
##  Median :5   Median :2
##  Mean   :4.13    Mean   :2.24
##  Max.   :10  Max.   :9
## 
## 95% HPD interval(non-piscivorous->piscivorous): [0, 8]
## 95% HPD interval(piscivorous->non-piscivorous): [0, 6]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.7}\NormalTok{,}
  \AttributeTok{cex.lab=}\FloatTok{0.8}\NormalTok{)}
\NormalTok{COLS}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(cols,sunfish.density}\SpecialCharTok{$}\NormalTok{trans)}
\FunctionTok{plot}\NormalTok{(sunfish.density,}\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.6}\NormalTok{),}
  \AttributeTok{transition=}\FunctionTok{names}\NormalTok{(COLS)[}\DecValTok{1}\NormalTok{],}\AttributeTok{colors=}\NormalTok{COLS[}\DecValTok{1}\NormalTok{],}
  \AttributeTok{main=}\StringTok{""}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"a) transitions to piscivory"}\NormalTok{,}\AttributeTok{line=}\DecValTok{1}\NormalTok{,}
  \AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(sunfish.density,}\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.6}\NormalTok{),}
  \AttributeTok{transition=}\FunctionTok{names}\NormalTok{(COLS)[}\DecValTok{2}\NormalTok{],}\AttributeTok{colors=}\NormalTok{COLS[}\DecValTok{2}\NormalTok{],}
  \AttributeTok{main=}\StringTok{""}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"b) transitions to non{-}piscivory"}\NormalTok{,}
  \AttributeTok{line=}\DecValTok{1}\NormalTok{,}\AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/num-changes-1} \caption{Posterior probability distributions of changes from either a) non-piscivory to piscivory, or b) piscivory to non-piscivory, obtained from an analysis of stochastic mapping. HPD indicates the 95\% high probability density interval for changes of each type. See main text for additional details.}\label{fig:num-changes}
\end{figure}

The distributions shown in Figure \ref{fig:num-changes} give the relative frequencies of changes of each type across our set of mapped histories, as well as Bayesian 95\% high probability density (HPD) intervals calculated using the R pakage \emph{coda} (Plummer et al. 2006).

An interesting attribute of the character state change distributions for our centrarchid feeding mode data is that they are both markedly bi-modal. This is due, in part, to our specific procedure of model-averaging in which we sampled both reversible and irreversible character evolution models in proportion to their weights, and isn't something we would've seen had we chosen to analyze just one model or the other. (Recall that the weight of evidence was highly similar between our equal-rates model and the irreversible model in which piscivory is acquired from non-piscivory, but never the reverse.)

Lastly, in addition to these analyses, \emph{phytools} also makes it quite straightforward to visualize the posterior probabilities of each of the two trait conditions not only at nodes, but also also along the branches of the phylogeny. This is accomplished using the \emph{phytools} function \texttt{densityMap} (Revell 2013), which creates a graph showing the probability density of stochastic histories in each of our mapped states. By design, in \emph{phytools} this object can be first created (using the \texttt{densityMap} function), updated (using the method \texttt{setMap} to adjust our color palette for plotting), and then graphed (using a generic \texttt{plot} method that was created for this specific object class).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sunfish.densityMap}\OtherTok{\textless{}{-}}\FunctionTok{densityMap}\NormalTok{(sunfish.simmap,}
  \AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{,}\AttributeTok{res=}\DecValTok{1000}\NormalTok{)}
\NormalTok{sunfish.densityMap}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Object of class "densityMap" containing:
## 
## (1) A phylogenetic tree with 28 tips and 27 internal nodes.
## 
## (2) The mapped posterior density of a discrete binary character
##     with states (non-piscivorous, piscivorous).
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sunfish.densityMap}\OtherTok{\textless{}{-}}\FunctionTok{setMap}\NormalTok{(sunfish.densityMap,}
\NormalTok{  viridisLite}\SpecialCharTok{::}\FunctionTok{viridis}\NormalTok{(}\AttributeTok{n=}\DecValTok{10}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(sunfish.densityMap,}\AttributeTok{lwd=}\DecValTok{3}\NormalTok{,}\AttributeTok{outline=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{fsize=}\FloatTok{0.7}\NormalTok{,}
  \AttributeTok{legend=}\FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/densityMap-1} \caption{Posterior probability density of each of the two character levels, piscivory and non-piscivory, mapped along the edges of a tree of centrarchid fishes. See main text for more details.}\label{fig:densityMap}
\end{figure}

\hypertarget{the-polymorphic-trait-evolution-model}{%
\subsection{The polymorphic trait evolution model}\label{the-polymorphic-trait-evolution-model}}

Another important, but much more recently-added, tool in the \emph{phytools} R package is a method (called \texttt{fitpolyMk}) that's designed to fit a discrete character evolution model to trait data containing intraspecific polymorphism (Revell and Harmon 2022). In this case, our model is one in which an evolutionary transition from (say) character state \emph{a} to character state \emph{b} must first pass through the intermediate polymorphic condition of \emph{a} + \emph{b}. This model starts off very simply -- but will become increasingly complicated for increasing numbers of monomorphic conditions of our trait. Not only that, but as soon as we have more than two monomorphic states, we must also consider whether our character is evolving in an ordered (Figure \ref{fig:structure-polyMk}a) or unordered (Figure \ref{fig:structure-polyMk}b) fashion (Revell and Harmon 2022).

Figure \ref{fig:structure-polyMk} shows the general structure of an ordered and unordered polymorphic trait evolution model -- both for the same number of monomorphic conditions of our trait (four).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{graph.polyMk}\NormalTok{(}\AttributeTok{k=}\DecValTok{4}\NormalTok{,}\AttributeTok{ordered=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{states=}\DecValTok{0}\SpecialCharTok{:}\DecValTok{3}\NormalTok{,}
  \AttributeTok{mar=}\FunctionTok{rep}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"a) ordered polymorphic model"}\NormalTok{,}\AttributeTok{line=}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}
  \AttributeTok{adj=}\FloatTok{0.2}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\FunctionTok{graph.polyMk}\NormalTok{(}\AttributeTok{k=}\DecValTok{4}\NormalTok{,}\AttributeTok{ordered=}\ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{states=}\NormalTok{letters[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{],}\AttributeTok{mar=}\FunctionTok{rep}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\DecValTok{4}\NormalTok{),}
  \AttributeTok{spacer=}\FloatTok{0.15}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"b) unordered polymorphic model"}\NormalTok{,}
  \AttributeTok{line=}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\AttributeTok{adj=}\FloatTok{0.2}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/structure-polyMk-1} \caption{Example structures of two alternative polymorphic trait evolution models for characters with four monomorphic conditions: a) an ordered model with states 0 to 3; b) an unordered model, with states \textit{a}, \textit{b}, \textit{c}, and \textit{d}. See main text for additional details.}\label{fig:structure-polyMk}
\end{figure}

Obviously, the potential parameter complexity of the unordered polymorphic trait evolution model is higher than the ordered model. Since there exists an unordered model that also has all ordered models as a special case, ordered and unordered models can be compared using likelihood-ratio tests (if nested) or information criteria.

To try out our polymorphic trait evolution model, let's use an excellent, recently-published dataset from Halali et al. (2020) consisting of a phylogenetic tree containing 287 Mycalesina butterfly species and data for butterfly habitat use. Halali et al. (2020) coded habitat as a polymorphic trait in which, for example, a species using both ``forest'' and forest ``fringe'' habitat would be coded as \texttt{"forest+fringe"}. In this case, our polymorphic trait evolution model will assume that to evolve from forest specialization to fringe specialization, a species must first (at least transiently) evolve through the polymorphic condition of using both habitats at once. This seems logical.

The Halali et al. (2020) dataset and tree now come packaged with the \emph{phytools} library, so both can be loaded using the \texttt{data} function, just as we've seen already for other datasets of this article.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(butterfly.tree)}
\FunctionTok{data}\NormalTok{(butterfly.data)}
\end{Highlighting}
\end{Shaded}

Let's begin by inspecting our data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(butterfly.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                     habitat
## Myc_francisca_formosana? forest+fringe+open
## Bic_cooksoni                           open
## Bic_brunnea                          forest
## Bic_jefferyi                    fringe+open
## Bic_auricruda_fulgida                forest
## Bic_smithi_smithi             forest+fringe
\end{verbatim}

\texttt{fitpolyMk} requires us to separate the different states in each polymorphic condition using the \texttt{+} symbol, but does not demand that our states be ordered in a consistent manner. In other words, \texttt{a+b} and \texttt{b+a} would be considered (properly) to be same polymorphic condition!

As a first preliminary step in our analysis, we can proceed to extract the column of habitat use data (\texttt{habitat} in our data frame) as a vector, and then print the different levels that it takes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.habitat}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}
\NormalTok{  butterfly.data}\SpecialCharTok{$}\NormalTok{habitat,}
  \FunctionTok{rownames}\NormalTok{(butterfly.data))}
\FunctionTok{print}\NormalTok{(}\FunctionTok{levels}\NormalTok{(butterfly.habitat))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "forest"             "forest+fringe"      "forest+fringe+open"
## [4] "fringe"             "fringe+open"        "open"
\end{verbatim}

Now, let's proceed to fit our polymorphic trait evolution model to these data.

In this instance, I'll fit a grand total of six different models. (This isn't a comprehensive set of the conceivable models for polymorphic data with these levels, but it seemed like a reasonable selection for illustrative purposes.)

The first three of these models all suppose that the evolution of my discrete character is totally unordered. Among this set, we'll imagine, first, equal transition rates between all monomorphic states or polymorphic conditions. For our second model, we'll permit all possible transition rates between states or state combinations to assume different values. Finally, for our third model we'll assume that the acquisition of polymorphism (or its increase) occurs with one rate, whereas the loss (or decrease) of polymorphism occurs with another, separate rate.

We refer to this last scenario as the ``transient model'' following Revell and Harmon (2022). The name for this model comes from the general notion that if the rate of loss exceeds the rate of gain, then polymorphism will typically be relatively transient in nature. Since polymorphism tends to be less frequently observed in the types of data that typify many phylogenetic comparative studies, including this model in our set seems like a reasonable idea.

To get our remaining three models, and reach the six total models that I promised at the outset of this section -- for each of the three listed above in which character evolution is unordered, we'll simply add a second \emph{ordered} model in which we assume that character evolution for our three monomorphic conditions tends to proceed as follows: \emph{forest} \(\leftrightarrow\) \emph{fringe} \(\leftrightarrow\) \emph{open} -- not forgetting, of course, about the intermediate polymorphic conditions that occur in between each of these monomorphic states!

To fit our first three models in R, we'll use the function \texttt{fitpolyMk} from the \emph{phytools} package as follows.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.ER\_unordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"ER"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## This is the design matrix of the fitted model.
## Does it make sense?
## 
##                    forest fringe open
## forest                  0      0    0
## fringe                  0      0    0
## open                    0      0    0 
## forest+fringe           1      1    0
## forest+open             1      0    1
## fringe+open             0      1    1
## forest+fringe+open      0      0    0
##                    forest+fringe forest+open fringe+open
## forest                         1           1           0
## fringe                         1           0           1
## open                           0           1           1
## forest+fringe                  0           0           0
## forest+open                    0           0           0
## fringe+open                    0           0           0
## forest+fringe+open             1           1           1
##                    forest+fringe+open
## forest                              0
## fringe                              0
## open                                0
## forest+fringe                       1
## forest+open                         1
## fringe+open                         1
## forest+fringe+open                  0
\end{verbatim}

By default, \texttt{fitpolyMk} prints out the design matrix of the model for us to verify. (The design matrix is of dimensions dictated by the number of states and polymorphic conditions of our character, with integers populating the different types of transitions, from row to column, that should be permitted under our model, and zeros indicating unallowed transition types. The specific integer values don't mean anything; however, different integer values imply that the corresponding transitions will be allowed to take place with different rates under our model.)

This can be helpful, because we should find that it corresponds with the design matrix that was discussed under the simpler M\emph{k} model of the previous section -- as well as with the graphed models of Figure \ref{fig:structure-polyMk}. If we don't want the design matrix to print, though, we can turn off this behavior simply by setting the optional argument \texttt{quiet=TRUE}.

Let's do that for our remaining two unordered models.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.ARD\_unordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"ARD"}\NormalTok{,}\AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{opt.method=}\StringTok{"optimParallel"}\NormalTok{,}\AttributeTok{rand\_start=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{butterfly.transient\_unordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"transient"}\NormalTok{,}\AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{opt.method=}\StringTok{"optimParallel"}\NormalTok{,}\AttributeTok{rand\_start=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Astute readers may notice that I added two additional arguments that didn't feature in my previous \texttt{fitpolyMk} function call: \texttt{opt.method="optimParallel"} and \texttt{rand\_start=TRUE}. The former tells my optimizer to use the \emph{optimParallel} package (Gerber and Furrer 2019) for optimization. The latter says ``choose random starting values.'' Both of these, and sometimes multiple optimization replicates, may be required to find our Maximum Likelihood solution for these complex models. (In fact, I virtually guarantee it!)

We're not done fitting models yet, but to see how things are going so far, why don't we compare our three fitted models using the generic \texttt{anova} method of their object class, as follows.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(butterfly.ER\_unordered,}
\NormalTok{  butterfly.ARD\_unordered,}
\NormalTok{  butterfly.transient\_unordered)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                  log(L) d.f.      AIC       weight
## butterfly.ER_unordered        -355.8122    1 713.6244 1.017751e-19
## butterfly.ARD_unordered       -295.0807   18 626.1614 1.000000e+00
## butterfly.transient_unordered -353.4496    2 710.8991 3.975914e-19
\end{verbatim}

This tells us that, just among the three models that we've considered to this point in our analysis, the best-supported by a wide margin is our parameter-rich all-rates-different (\texttt{"ARD"}) model.

Now we can proceed to do the same thing, but this time updating the argument value \texttt{ordered} to \texttt{ordered=TRUE}; however, when we switch from fitting an unordered polymorphic trait evolution model to our ordered model, it suddenly becomes critical that we specify the order levels using the optional function argument \texttt{order}. If \texttt{order} isn't indicated, \texttt{fitpolyMk} will simply assume that our characters are ordered alphanumerically -- but this is very rarely likely to be correct! (By chance, it happens to be true of our butterfly dataset. I assigned the argument \texttt{order} anyway, just to be safe!)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{levs}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(}\StringTok{"forest"}\NormalTok{,}\StringTok{"fringe"}\NormalTok{,}\StringTok{"open"}\NormalTok{)}
\NormalTok{levs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "forest" "fringe" "open"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.ER\_ordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"ER"}\NormalTok{,}\AttributeTok{ordered=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{order=}\NormalTok{levs,}
  \AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{butterfly.ARD\_ordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"ARD"}\NormalTok{,}\AttributeTok{ordered=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{order=}\NormalTok{levs,}
  \AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{opt.method=}\StringTok{"optimParallel"}\NormalTok{,}
  \AttributeTok{rand\_start=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{butterfly.transient\_ordered}\OtherTok{\textless{}{-}}\FunctionTok{fitpolyMk}\NormalTok{(}
\NormalTok{  butterfly.tree,butterfly.habitat,}
  \AttributeTok{model=}\StringTok{"transient"}\NormalTok{,}\AttributeTok{ordered=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{order=}\NormalTok{levs,}\AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{opt.method=}\StringTok{"optimParallel"}\NormalTok{,}
  \AttributeTok{rand\_start=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now, with all six models in hand, let's compare them using a second \texttt{anova} call as follows. This time I'll save my results from our model comparison to the object \texttt{butterfly.aov}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.aov}\OtherTok{\textless{}{-}}\FunctionTok{anova}\NormalTok{(butterfly.ER\_ordered,}
\NormalTok{  butterfly.ER\_unordered,}
\NormalTok{  butterfly.transient\_ordered,}
\NormalTok{  butterfly.transient\_unordered,}
\NormalTok{  butterfly.ARD\_ordered,}
\NormalTok{  butterfly.ARD\_unordered)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                  log(L) d.f.      AIC       weight
## butterfly.ER_ordered          -329.0390    1 660.0779 1.472873e-09
## butterfly.ER_unordered        -355.8122    1 713.6244 3.472845e-21
## butterfly.transient_ordered   -329.0205    2 662.0409 5.519508e-10
## butterfly.transient_unordered -353.4496    2 710.8991 1.356691e-20
## butterfly.ARD_ordered         -297.7376   12 619.4753 9.658773e-01
## butterfly.ARD_unordered       -295.0807   18 626.1614 3.412273e-02
\end{verbatim}

A quick word of caution to readers is probably merited. These models can be quite difficult to optimize, meaning that it's not inconceivable to imagine that (in spite of our best efforts) \texttt{fitpolyMk} hasn't converged on the true Maximum Likelihood solution for one model or another. Although the true best solution may be unknowable (this is why we use numerical optimization to try and ascertain it), common sense can be a valuable defense against very obvious failures of optimization. For instance, had we found that the most complex model (in our case, \texttt{butterfly.ARD\_unordered}) had a lower likelihood than its nested counterparts (for instance, \texttt{butterfly.ARD\_ordered}), this would give us very strong cause to believe that one or both models hadn't converged, and that we should perhaps try different random starts or alternative optimization routines to try to find better solutions!

Nonetheless, taking our fitted models at face value, model comparison shows that (among the models in our set) the best supported by far is the ordered, all-rates-different model. \emph{phytools} has a function to graph this model, so let's go ahead and use it!

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(butterfly.ARD\_ordered,}\AttributeTok{asp=}\FloatTok{0.65}\NormalTok{,}
  \AttributeTok{mar=}\FunctionTok{rep}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\DecValTok{4}\NormalTok{),}\AttributeTok{cex.traits=}\FloatTok{0.8}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\StringTok{"bottomleft"}\NormalTok{,}\AttributeTok{legend=}\FunctionTok{c}\NormalTok{(}
  \FunctionTok{paste}\NormalTok{(}\StringTok{"log(L) ="}\NormalTok{,}
  \FunctionTok{round}\NormalTok{(}\FunctionTok{logLik}\NormalTok{(butterfly.ARD\_ordered),}\DecValTok{2}\NormalTok{)),}
  \FunctionTok{paste}\NormalTok{(}\StringTok{"AIC ="}\NormalTok{,}
  \FunctionTok{round}\NormalTok{(}\FunctionTok{AIC}\NormalTok{(butterfly.ARD\_ordered),}\DecValTok{2}\NormalTok{))),}
  \AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/ordered-ard-fitpolyMk-1} \caption{Best-fitting polymorphic trait evolution model for the evolution of habitat use in Mycalesina butterflies.}\label{fig:ordered-ard-fitpolyMk}
\end{figure}

Just as with our fitted M\emph{k} models from the prior section, we can also pass this model object to our generic stochastic character mapping method, \texttt{simmap}. When we do, \texttt{simmap} will automatically generate a set of 100 stochastic character maps under our fitted model. (We could've likewise passed \texttt{simmap} our \texttt{anova} results, just as we did with our \texttt{"fitMk"} objects in the centrarchid example, above. In this case, however, nearly all the weight of evidence fell on one model: our ordered, all-rates-different model.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.simmap}\OtherTok{\textless{}{-}}\FunctionTok{simmap}\NormalTok{(butterfly.ARD\_ordered)}
\NormalTok{butterfly.simmap}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 100 phylogenetic trees with mapped discrete characters
\end{verbatim}

Now that we have our stochastically mapped trees, let's compute a summary, just as we did in the prior section.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.summary}\OtherTok{\textless{}{-}}\FunctionTok{summary}\NormalTok{(butterfly.simmap)}
\end{Highlighting}
\end{Shaded}

Much as we saw earlier, the object from our generic \texttt{summary} call can be conveniently plotted using \emph{phytools}. Here I'll use the base graphics function \texttt{rgb} to attempt to select colors for plotting that are evenly spaced in a red-green-blue color space in which the ``corners'' (red, green, and blue) correspond to the three monomorphic states of our data. Does that make sense? (I'm colorblind, so it's hard for me to be sure how the \texttt{rgb} color space captures the ``intermediacy'' of the polymorphic conditions between the corresponding monomorphic states.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hab.cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\FunctionTok{rgb}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{),}
  \FunctionTok{rgb}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.5}\NormalTok{,}\FloatTok{0.5}\NormalTok{),}\FunctionTok{rgb}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{,}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{,}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{),}
  \FunctionTok{rgb}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{),}\FunctionTok{rgb}\NormalTok{(}\FloatTok{0.5}\NormalTok{,}\FloatTok{0.5}\NormalTok{,}\DecValTok{0}\NormalTok{),}
  \FunctionTok{rgb}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{)),}\FunctionTok{levels}\NormalTok{(butterfly.habitat))}
\FunctionTok{par}\NormalTok{(}\AttributeTok{fg=}\StringTok{"transparent"}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(butterfly.summary,}\AttributeTok{type=}\StringTok{"fan"}\NormalTok{,}
  \AttributeTok{ftype=}\StringTok{"off"}\NormalTok{,}\AttributeTok{colors=}\NormalTok{hab.cols,}
  \AttributeTok{cex=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{,}\FloatTok{0.2}\NormalTok{),}\AttributeTok{part=}\FloatTok{0.5}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{1}\NormalTok{)}
\FunctionTok{par}\NormalTok{(}\AttributeTok{fg=}\StringTok{"black"}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{,}\FunctionTok{names}\NormalTok{(hab.cols),}\AttributeTok{pch=}\DecValTok{21}\NormalTok{,}
  \AttributeTok{pt.bg=}\NormalTok{hab.cols,}\AttributeTok{pt.cex=}\FloatTok{1.5}\NormalTok{,}
  \AttributeTok{cex=}\FloatTok{0.8}\NormalTok{,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/anc-fitpolyMk-1} \caption{Posterior probabilities of monomorphic or polymorphic conditions at internal nodes from stochastic mapping under an ordered, ARD model of trait evolution. See main text for additional details.}\label{fig:anc-fitpolyMk}
\end{figure}

Excellent! Figure \ref{fig:anc-fitpolyMk} shows both the observed (at the tips) and reconstructed (at the internal nodes) marginal posterior probabilities for each of our states and polymorphic conditions.

Lastly, let's graph the posterior distribution of the accumulation of lineages in each state over time, using the \emph{phytools} function \texttt{ltt} as follows. (We'll learn more about \texttt{ltt} in a subsequent section.) We can even do this while retaining the same color palette as we used for Figure \ref{fig:anc-fitpolyMk}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{butterfly.ltt}\OtherTok{\textless{}{-}}\FunctionTok{ltt}\NormalTok{(butterfly.simmap)}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{5.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(butterfly.ltt,}\AttributeTok{show.total=}\ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.7}\NormalTok{,}
  \AttributeTok{cex.lab=}\FloatTok{0.8}\NormalTok{,}\AttributeTok{colors=}\NormalTok{hab.cols)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/ltt-fitpolyMk-1} \caption{Lineage-through-time plot showing the reconstructed accumulation of lineages in each polymorphic condition or monomorphic state over time, from 100 stochastic character maps. See main text for additional details.}\label{fig:ltt-fitpolyMk}
\end{figure}

The plot of Figure \ref{fig:ltt-fitpolyMk} simultaneously shows the accumulation of lineages in each mono- or polymorphic state, but also the variation attributable to uncertainty in the evolutionary history of our group from our stochastic character maps! (Even though Figure \ref{fig:ltt-fitpolyMk} looks very cool -- to be fair, this type of graph is only especially meaningful for the situation in which the taxa of our phylogeny have been completely sampled. Though this is unlikely to be true here, I felt that it was nonetheless interesting to demonstrate!)

\hypertarget{continuous-characters}{%
\section{Continuous characters}\label{continuous-characters}}

Numerous continuous trait methods exist in the \emph{phytools} package. For example, \emph{phytools} can be used to measure phylogenetic signal (\texttt{phylosig}, Pagel 1999; Blomberg et al. 2003; Revell et al. 2008), it can fit multi-rate Brownian evolution models (\texttt{brownie.lite}, \texttt{brownieREML}, \texttt{evol.rate.mcmc}, \texttt{multirateBM}, \texttt{ratebytree}, and \texttt{rateshift}, O'Meara et al. 2006; Revell et al. 2012, 2018; Revell 2021; Revell and Harmon 2022), it can perform phylogenetic canonical correlation and principal components analysis (\texttt{phyl.cca} and \texttt{phyl.pca}, Revell and Harrison 2008; Revell 2009), it can reconstruct ancestral states under multiple evolutionary models (\texttt{anc.Bayes}, \texttt{anc.ML}, \texttt{anc.trend}, and \texttt{fastAnc}, Schluter et al. 1997; Revell and Harmon 2022), it can use continuous trait data to place a fossil or missing lineage into a reconstructed tree (\texttt{locate.fossil} and \texttt{locate.yeti}, Felsenstein 2002; Revell et al. 2015), it can fit a multivariate Brownian model with multiple evolutionary correlations on the tree (\texttt{evol.vcv} and \texttt{evolvcv.lite}, Revell and Collar 2009; Revell et al. 2022), and it can perform various types of continuous character numerical simulation on phylogenies (e.g., \texttt{branching.diffusion}, \texttt{fastBM}, \texttt{sim.corrs}, \texttt{sim.rates}).

Here I'll start by illustrating the measurement of phylogenetic signal (\texttt{phylosig}), then I'll demonstrate Bayesian ancestral state estimation (\texttt{anc.Bayes}). I'll show how to fit a variable-correlation multivariate Brownian trait evolution model (\texttt{evolvcv.lite}), and, finally, I'll demonstrate a relatively new multi-rate trait evolution model that uses the estimation technique of penalized likelihood (\texttt{multirateBM}).

\hypertarget{phylogenetic-signal}{%
\subsection{Phylogenetic signal}\label{phylogenetic-signal}}

Perhaps the simplest phylogenetic comparative analysis that we could choose to undertake for a continuous trait data in R is the measurement of phylogenetic signal (Pagel 1999; Blomberg et al. 2003; Revell et al. 2008).

Phylogenetic signal has been defined in a number of different ways, but could be considered to be the simple tendency of more closely related species to bear more similarity (one to another) than they do to more distant taxa. Phylogenetic signal can be quantified in various manners, but undoubtedly the two most popular metrics are Blomberg et al.'s (2003) \emph{K} statistic, and Pagel's (1999) \(\lambda\). Conveniently, both of these can be calculated using the \emph{phytools} package.

To get started in this undertaking, let's load some data from \emph{phytools} consisting of a phylogenetic tree of elopomorph eels and a data frame of phenotypic traits. Both tree and data were obtained from an article by Collar et al. (2014).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(eel.tree)}
\FunctionTok{data}\NormalTok{(eel.data)}
\FunctionTok{head}\NormalTok{(eel.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   feed_mode Max_TL_cm
## Albula_vulpes       suction       104
## Anguilla_anguilla   suction        50
## Anguilla_bicolor    suction       120
## Anguilla_japonica   suction       150
## Anguilla_rostrata   suction       152
## Ariosoma_anago      suction        60
\end{verbatim}

Having loaded these data, we can next extract one variable from our data array. Phylogenetic signal can be measured for any continuous trait, so we'll use maximum total length: here represented by the column of our data frame called \texttt{"Max\_TL\_cm"}. As is often the case, we'll transform our data to a log scale. (There are multiple reasons log transformations are favored by comparative biologists working on interspecies data. One is that it makes a, say, 10\% change equal, regardless of whether it occurs in an elephant or a mouse! See Revell and Harmon 2022 for more details.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eel.lnTL}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}\FunctionTok{log}\NormalTok{(eel.data}\SpecialCharTok{$}\NormalTok{Max\_TL\_cm),}
  \FunctionTok{rownames}\NormalTok{(eel.data))}
\end{Highlighting}
\end{Shaded}

Next, we'll compute a value of the \emph{K} statistic of Blomberg et al. (2003) using the \emph{phytools} function \texttt{phylosig}. \texttt{phylosig} calculates \emph{K} by default (that is, without specifying an argument for \texttt{method}), but if I add the argument value \texttt{test=TRUE}, \texttt{phylosig} will also conduct a statistical test of the measured value of \emph{K} by comparing it to a null distribution of \emph{K} obtained by permuting our observed trait values randomly across the tips of the phylogeny.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eel.Blomberg\_K}\OtherTok{\textless{}{-}}\FunctionTok{phylosig}\NormalTok{(eel.tree,eel.lnTL,}
  \AttributeTok{test=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{eel.Blomberg\_K}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Phylogenetic signal K : 0.362879 
## P-value (based on 1000 randomizations) : 0.034
\end{verbatim}

\emph{K} has an expected value of 1.0 under Brownian motion (Blomberg et al. 2003). The lower value that we observe here thus indicates less phylogenetic signal than expected under Brownian evolution; whereas a value higher than 1.0 would've indicated more. Our significance test shows us that this value of \emph{K}, though modest, is nonetheless significantly greater than we'd expect to find in data that were entirely random with respect to the tree!

In addition to Blomberg et al.'s \emph{K}, \emph{phytools} also can be used to estimate Pagel's (1999) \(\lambda\) statistic. \(\lambda\) measures phylogenetic signal as a scalar multiplier of the correlations of related taxa in our tree (Revell and Harmon 2022). That is to say, if \(\lambda\) has a value less than 1.0, this would indicate that related species in our phylogeny have a lower degree of ``autocorrelation'' than expected under Brownian evolution. In fact, a value of \(\lambda\) close to zero could be taken to indicate that related species are not phenotypically correlated at all!

We use Maximum Likelihood to find the value of \(\lambda\) that makes our observed data most probable. Since it's possible to compute a likelihood for any allowable value of \(\lambda\), including \(\lambda\) = 0, we can very easily proceed to test a null hypothesis of no phylogenetic signal in our data by simply calculating a likelihood ratio in which we compare \(\lambda\) = 0 to our Maximum Likelihood estimate. Indeed, this is the test performed by \emph{phytools} if \texttt{method="lambda"} and \texttt{test=TRUE}!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{eel.Pagel\_lambda}\OtherTok{\textless{}{-}}\FunctionTok{phylosig}\NormalTok{(eel.tree,eel.lnTL,}
  \AttributeTok{method=}\StringTok{"lambda"}\NormalTok{,}\AttributeTok{test=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{eel.Pagel\_lambda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Phylogenetic signal lambda : 0.673735 
## logL(lambda) : -54.3016 
## LR(lambda=0) : 5.18173 
## P-value (based on LR test) : 0.0228256
\end{verbatim}

This result tells us that we've found significant phylogenetic signal in our trait by both measures. Although \emph{K} and \(\lambda\) tend to be correlated, it's entirely possible that we could've found significant \emph{K} and non-significant \(\lambda\), or vice versa. This is not a contradiction. The concept of phylogenetic signal is one of phenotypic similarity among related species -- but \emph{K} and \(\lambda\) measure this concept via two entirely different procedures!

Along with the simple calculation of phylogenetic signal, \emph{phytools} also contains several methods to visualize our results. In particular, for Blomberg et al.'s \emph{K} we can plot the permutation distribution of \emph{K} alongside our observed measure. For Pagel's \(\lambda\), we can plot the likelihood surface, our Maximum Likelihood solution, and the likelihood of \(\lambda\) = 0: the null hypothesis of our statistical tests. Both of these plots are illustrated in Figure \ref{fig:phylosig} for our eel body length data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{cex=}\FloatTok{0.9}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(eel.Blomberg\_K,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.9}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"a)"}\NormalTok{,}\AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{line=}\DecValTok{1}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(eel.Pagel\_lambda,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}
  \AttributeTok{cex.axis=}\FloatTok{0.9}\NormalTok{,}\AttributeTok{xlim=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{1.1}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"b)"}\NormalTok{,}\AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{line=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/phylosig-1} \caption{a) Blomberg et al. (2003) measured value of the \textit{K} statistic for phylogenetic signal, compared to a null distribution of \textit{K} obtained via randomization. b) Pagel's (1999) $\lambda$ statistic for phylogenetic signal, also showing the likelihood surface. Data consist of maximum body length (on a log scale) from 61 species of elopomorph eels. See main text for additional details.}\label{fig:phylosig}
\end{figure}

\hypertarget{bayesian-ancestral-state-estimation}{%
\subsection{Bayesian ancestral state estimation}\label{bayesian-ancestral-state-estimation}}

The \emph{phytools} package contains several different functions for discrete and continuous character ancestral state estimation under multiple models. Earlier, we reviewed the method of stochastic character mapping (Huelsenbeck et al. 2003) which can be an important tool for ancestral state reconstruction of discrete characters.

Among the variety of approaches for ancestral character estimation of continuous characters that are implemented in the \emph{phytools} package is the function \texttt{anc.Bayes}. As its name suggests, \texttt{anc.Bayes} performs ancestral state estimation using Bayesian MCMC. Just as any proper Bayesian approach should, the implementation of this method allows us to include prior information about the states at internal nodes. Here, I'll illustrate the simplest type of analysis that we can undertake with the function in which I'll simply accept the default node priors and MCMC conditions. \texttt{anc.Bayes}, however, will be most useful when we intend to explicitly incorporate prior knowledge about internal nodes of the tree -- based on, for instance, observations from the fossil record.

To demonstrate the method, I'll load a dataset (now packaged with \emph{phytools}) that consists of a phylogeny and phenotypic trait information for a set of lizards from the family Cordylidae, originally published by Broeckhoven et al. (2016).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(cordylid.tree)}
\FunctionTok{data}\NormalTok{(cordylid.data)}
\FunctionTok{head}\NormalTok{(cordylid.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    pPC1     pPC2     pPC3
## C._aridus       0.59441 -0.40209  0.57109
## C._minor        0.65171 -0.32732  0.55692
## C._imkeae       0.19958 -0.08978  0.56671
## C._mclachlani   0.62065  0.03746  0.86721
## C._macropholis  0.44875 -0.75942  0.09737
## C._cordylus    -0.07267  0.48294 -0.54394
\end{verbatim}

Our trait data in this case are species scores for three different principal component (PC) axes from a phylogenetic principal components analysis undertaken using the \emph{phytools} \texttt{phyl.pca} function (Revell 2009). Cordylid lizards are known for their body and tail armor, consisting of large, rectangular scales called osteoderms. Principal component 1 in Broeckhoven et al. (2016) separated the most lightly armored cordylids (large negative values), from those cordylids with the heaviest body armor (large positive values of PC 1). Why don't we extract this principal component from our data frame and rename it, as follows?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cordylid.armor\_score}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}
\NormalTok{  cordylid.data}\SpecialCharTok{$}\NormalTok{pPC1,}\FunctionTok{rownames}\NormalTok{(cordylid.data))}
\end{Highlighting}
\end{Shaded}

With this named trait vector at the ready, we're prepared to undertake our Bayesian MCMC. As noted above, we'll use the default conditions but update the number of generations that we want our MCMC to run to \texttt{ngen=500000}. Depending on the size of our phylogenetic tree, we may want to run more (or fewer) generations in a genuine empirical study.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cordylid.mcmc}\OtherTok{\textless{}{-}}\FunctionTok{anc.Bayes}\NormalTok{(cordylid.tree,}
\NormalTok{  cordylid.armor\_score,}\AttributeTok{ngen=}\DecValTok{500000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## List of 7
##  $ sig2   : num 0.713
##  $ a      : num [1, 1] 0.000422
##  $ y      : num [1:26] 0.000422 0.000422 0.000422 0.000422 ...
##  $ pr.mean: num [1:28] 1000 0 0 0 0 0 0 0 0 0 ...
##  $ pr.var : num [1:28] 1e+06 1e+03 1e+03 1e+03 1e+03 ...
##  $ prop   : num [1:28] 0.00713 0.00713 0.00713 0.00713 ...
##  $ sample : num 100

## Starting MCMC...

## Done MCMC.
\end{verbatim}

We can see that the method starts by printing out a summary of the ``control parameters'' of the MCMC. These include information about our prior probability distributions, the variances of the proposal distributions, and, finally, the interval that we'll use to sample from our posterior. All of these parameters can be adjusted by the \emph{phytools} user.

The object class that results from this function call (\texttt{"anc.Bayes"}) has a \texttt{summary} method in \emph{phytools} that prints the mean from the posterior distribution, automatically excluding the first 20\% of our samples as burn-in (though we can adjust this percentage if we'd like). It also passes the estimates (normally invisibly, but we can save them to a new variable in our workspace as we've done here) back to the user.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cordylid.ace}\OtherTok{\textless{}{-}}\FunctionTok{summary}\NormalTok{(cordylid.mcmc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Object of class "anc.Bayes" consisting of a posterior
##    sample from a Bayesian ancestral state analysis:
## 
## Mean ancestral states from posterior distribution:
##        29        30        31        32        33        34 
##  0.059277 -0.099027 -0.106452  0.057220  0.153671  0.201722 
##        35        36        37        38        39        40 
##  0.225081  0.297659  0.392992  0.493316  0.015503 -0.006053 
##        41        42        43        44        45        46 
##  0.435309  0.392526  0.300532  0.210391 -1.505181 -1.857682
##        47        48        49        50        51        52
## -0.136014 -0.520322 -0.829181 -0.985510 -1.040208  0.385293
##        53        54        55 
##  0.511646  0.159943  0.028358 
## 
## Based on a burn-in of 1e+05 generations.
\end{verbatim}

Now that we've obtained our estimated Bayesian ancestral states for internal nodes, it's a straightforward task to visualize them on the branches and nodes of the tree. For this undertaking we'll use the popular \emph{phytools} plotting function \texttt{contMap} (Revell 2013). By default, \texttt{contMap} uses Maximum Likelihood to compute ancestral states at all of the internal nodes of the tree -- but it can also be supplied with user-specified values. Since we want to use our Bayesian estimates from \texttt{anc.Bayes}, that's what we'll do here.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cordylid.contMap}\OtherTok{\textless{}{-}}\FunctionTok{contMap}\NormalTok{(cordylid.tree,}
\NormalTok{  cordylid.armor\_score,}\AttributeTok{anc.states=}\NormalTok{cordylid.ace,}
  \AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{)}
\NormalTok{cordylid.contMap}\OtherTok{\textless{}{-}}\FunctionTok{setMap}\NormalTok{(cordylid.contMap,}
\NormalTok{  viridisLite}\SpecialCharTok{::}\FunctionTok{viridis}\NormalTok{(}\AttributeTok{n=}\DecValTok{10}\NormalTok{,}\AttributeTok{direction=}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(cordylid.contMap,}\AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}\AttributeTok{fsize=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.8}\NormalTok{),}
  \AttributeTok{leg.txt=}\StringTok{"PC 1 (increasing armor)"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{3}\NormalTok{)}
\FunctionTok{nodelabels}\NormalTok{(}\AttributeTok{frame=}\StringTok{"circle"}\NormalTok{,}\AttributeTok{bg=}\StringTok{"white"}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/cordylid-ace-1} \caption{Reconstructed ancestral values from Bayesian MCMC projected onto the nodes and edges of the tree. Numerical values at internal nodes are node indices from our input phylogeny. Data consist of PC 1 from a phylogenetic principal components analysis of cordylid morphological trait, and separate highly armored (high values) from lightly armored (low values) lizards. See main text for more details.}\label{fig:cordylid-ace}
\end{figure}

(For fun, compare Figure \ref{fig:cordylid-ace} to Figure 2 of Broeckhoven et al.~in which estimated ancestral state values were assigned to each branch using a similar color gradient!)

In addition to this simple analysis, we can (naturally) extract and plot posterior probability densities from any of our internal nodes of the tree. To see this, let's focus on the node labeled ``49'' in Figure \ref{fig:cordylid-ace} and do exactly that. Node 49 corresponds to the common ancestor of the \emph{Pseudocordylus} clade, which is among the least heavily armored of all cordylids in our tree, so we'd expect our posterior distribution for this node to be centered on a relatively low value for our armor score.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cordylid.node49}\OtherTok{\textless{}{-}}\FunctionTok{density}\NormalTok{(cordylid.mcmc,}
  \AttributeTok{what=}\DecValTok{49}\NormalTok{)}
\NormalTok{cordylid.node49}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
##  density.anc.Bayes(x = cordylid.mcmc, what = 49)
## 
## Data: node 49 (4001 obs.);   Bandwidth 'bw' = 0.05679
## 
##        x                 y           
##  Min.   :-2.1658   Min.   :0.000023  
##  1st Qu.:-1.5270   1st Qu.:0.022415  
##  Median :-0.8883   Median :0.187932  
##  Mean   :-0.8883   Mean   :0.391002  
##  3rd Qu.:-0.2495   3rd Qu.:0.784591  
##  Max.   : 0.3893   Max.   :1.187968
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{5.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(cordylid.node49,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{main=}\StringTok{""}\NormalTok{,}
  \AttributeTok{cex.lab=}\FloatTok{0.9}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.8}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"PC 1 (increasing armor)"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"Posterior density"}\NormalTok{,}
  \AttributeTok{xlim=}\FunctionTok{range}\NormalTok{(cordylid.armor\_score))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/cordylid-pd-1} \caption{Posterior probability density at node 49 of Figure 10 from Bayesian MCMC ancestral state reconstruction of PC 1 from a morphological analysis on a phylogenetic tree of cordylid lizards. Node 49 corresponds to the common ancestor of the \textit{Pseudocordylus}: a relatively lightly armored cordylid clade. See main text for more details.}\label{fig:cordylid-pd}
\end{figure}

Figure \ref{fig:cordylid-pd} shows our estimate of the posterior probability distribution of the ancestral node 49 state, and should be centered precisely on the value we projected onto the tree of Figure \ref{fig:cordylid-ace}!

\hypertarget{multivariate-trait-evolution}{%
\subsection{Multivariate trait evolution}\label{multivariate-trait-evolution}}

Along with the various univariate methods we've seen so far, \emph{phytools} also contains a handful of different multivariate trait evolution models, designed for both continuous and discrete characters.

One of these is an interesting model (described in Revell and Collar 2009; Revell et al. 2022) in which the rates and evolutionary correlations between traits are allowed to vary as a function of a set of mapped regimes on the tree. (Similar to O'Meara et al. 2006, but for more than one trait at a time.) The underlying motivation of this method is to test hypotheses about phylogenetic heterogeneity in the evolutionary relationship (i.e., correlation) between different traits on our phylogeny.

To illustrate the method, I'll use a phylogenetic tree and dataset of tropidurid lizard species from Revell et al. (2022).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(tropidurid.tree)}
\FunctionTok{data}\NormalTok{(tropidurid.data)}
\end{Highlighting}
\end{Shaded}

In this case, our phylogeny is already a tree with mapped regimes. We can see this by merely printing the model object that we loaded. (In an empirical study we might imagine using a set of such trees sampled in proportion to their probabilities using stochastic mapping -- and then averaging the result. E.g., see Revell et al. 2022.)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(tropidurid.tree,}\AttributeTok{printlen=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Phylogenetic tree with 76 tips and 75 internal nodes.
## 
## Tip labels:
##  Leiocephalus_raviceps, Leiocephalus_carinatus, ...
## 
## The tree includes a mapped, 2-state discrete character
## with states:
##  n_rock, rock
## 
## Rooted; includes branch lengths.
\end{verbatim}

This tells us that our phylogenetic tree contains 76 taxa and a mapped regime with two states: \texttt{"n\_rock"} (non-rock dwelling) and \texttt{"rock"} (rock-dwelling). Since \emph{phytools} permits mapped regimes to have arbitrary names, let's rename these levels in a more informative way. To do so, I'll use the \emph{phytools} function \texttt{mergeMappedTraits}. \texttt{mergeMappedTraits}, as readers can probably guess, is designed to merge the mappings of two or more traits into one -- but can also be employed to simply substitute one mapping name for another.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tropidurid.tree}\OtherTok{\textless{}{-}}\FunctionTok{mergeMappedStates}\NormalTok{(}
\NormalTok{  tropidurid.tree,}\StringTok{"n\_rock"}\NormalTok{,}\StringTok{"non{-}rock dwelling"}\NormalTok{)}
\NormalTok{tropidurid.tree}\OtherTok{\textless{}{-}}\FunctionTok{mergeMappedStates}\NormalTok{(}
\NormalTok{  tropidurid.tree,}\StringTok{"rock"}\NormalTok{,}\StringTok{"rock{-}dwelling"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let's plot this updated tree. To do so, I'm going to use the recent \emph{phytools} function \texttt{sigmoidPhylogram} that will plot our tree using curved (``sigmoidal'') linking lines. (\emph{phytools} contains lots of cool functions like this one!)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"white"}\NormalTok{,}\StringTok{"black"}\NormalTok{),}\FunctionTok{c}\NormalTok{(}\StringTok{"non{-}rock dwelling"}\NormalTok{,}
  \StringTok{"rock{-}dwelling"}\NormalTok{))}
\FunctionTok{sigmoidPhylogram}\NormalTok{(tropidurid.tree,}
  \AttributeTok{direction=}\StringTok{"upwards"}\NormalTok{,}\AttributeTok{outline=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{colors=}\NormalTok{cols,}\AttributeTok{direction=}\StringTok{"upwards"}\NormalTok{,}
  \AttributeTok{outline=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}\AttributeTok{fsize=}\FloatTok{0.4}\NormalTok{,}
  \AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}\AttributeTok{offset=}\DecValTok{1}\NormalTok{)}
\FunctionTok{legend}\NormalTok{(}\StringTok{"bottomright"}\NormalTok{,}\FunctionTok{c}\NormalTok{(}\StringTok{"non{-}rock dwelling"}\NormalTok{,}
  \StringTok{"rock{-}dwelling"}\NormalTok{),}\AttributeTok{pch=}\DecValTok{22}\NormalTok{,}\AttributeTok{pt.bg=}\NormalTok{cols,}
  \AttributeTok{cex=}\FloatTok{0.8}\NormalTok{,}\AttributeTok{pt.cex=}\FloatTok{1.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/trop-tree-1} \caption{Phylogenetic tree of rock- and non-rock dwelling tropidurid lizard species from Revell et al. (2022). See main text for more details.}\label{fig:trop-tree}
\end{figure}

The phenotypic trait data in \texttt{tropidurid.data} consist of a single measure of overall body size (as trait 1, \texttt{"new\_size"}), and a second metric trait measuring dorsoventral depth (vs.~flattening, \texttt{"body\_height"}).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(tropidurid.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            newsize body_height
## Leiocephalus_raviceps     2.358317  0.05768818
## Leiocephalus_carinatus    2.931721  0.30216220
## Leiocephalus_psammodromus 2.700397  0.19667083
## Leiocephalus_personatus   2.535315  0.32216983
## Leiocephalus_barahonensis 2.473666  0.30266917
## Stenocercus_ochoai        2.549010  0.29067644
\end{verbatim}

Our hypothesis of multivariate trait evolution in this clade is that these two traits (size and body depth) should generally scale together in non-rock dwelling lizard species: bigger lizards also tend to have larger body depths. We hypothesize, however, that this general relationship may become decoupled in rock-dwelling lineages where the force of selection is predicted to favor increased flattening, relative to their non-rock dwelling kin. (There are biomechanical and behavioral reasons to suspect this could be so. For more information, see Revell et al. 2007; Revell et al. 2022.)

To test this hypothesis, we'll use the \emph{phytools} function \texttt{evolvcv.lite} which fits a heirarchical set of models for the evolutionary rates (of each character) and evolutionary correlations (between them, Revell et al. 2022).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tropidurid.fits}\OtherTok{\textless{}{-}}\FunctionTok{evolvcv.lite}\NormalTok{(tropidurid.tree,}
\NormalTok{  tropidurid.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fitting model 1: common rates, common correlation...
## Best log(L) from model 1: 52.3056.
## Fitting model 2: different rates, common correlation...
## Best log(L) from model 2: 54.3968.
## Fitting model 3: common rates, different correlation...
## Best log(L) from model 3: 55.1105.
## Fitting model 4: no common structure...
## Best log(L) from model 4: 56.2877.
\end{verbatim}

Having fit each of four models (in this case: \texttt{evolvcv.lite} actually includes several additional models that we won't review here, see Revell et al. 2022 for more details), we can most easily compare all of the models in our set using a generic \texttt{anova} function call as follows.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(tropidurid.fits)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           log(L) d.f.       AIC     weight
## model 1 52.30560    5 -94.61119 0.09221085
## model 2 54.39681    7 -94.79362 0.10101737
## model 3 55.11048    6 -98.22096 0.56057433
## model 4 56.28765    8 -96.57530 0.24619745
\end{verbatim}

This comparison shows us that \texttt{"model\ 3"} is the best-supported explanation of our data in this set. Indeed, this model is one in which the evolutionary covariance between overall body size and dorsoventral flattening is negative among rock-dwelling lineages -- compared to the positive evolutionary covariance in non-rock species and across all other models, just as we'd predicted. Size and body depth are indeed evolutionarily decoupled in rock-dwelling forms!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tropidurid.fits}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Model 1: common rates, common correlation 
##  R[1,1]  R[1,2]  R[2,2]  k   log(L)  AIC
## fitted   0.2224  0.0154  0.0589  5   52.3056 -94.6112    
## 
## (R thinks it has found the ML solution for model 1.)
## 
## Model 2: different rates, common correlation
##  R[1,1]  R[1,2]  R[2,2]  k   log(L)  AIC
## non-rock dwelling    0.2025  0.0187  0.0456  7   54.3968 -94.7936    
## rock-dwelling    0.3043  0.0382  0.1263  
## 
## (R thinks it has found the ML solution for model 2.)
## 
## Model 3: common rates, different correlation
##  R[1,1]  R[1,2]  R[2,2]  k   log(L)  AIC
## non-rock dwelling    0.2256  0.0394  0.0588  6   55.1105 -98.221 
## rock-dwelling    0.2256  -0.0354 0.0588  
## 
## (R thinks it has found the ML solution for model 3.)
## 
## Model 4: no common structure
##  R[1,1]  R[1,2]  R[2,2]  k   log(L)  AIC
## non-rock dwelling    0.2108  0.0325  0.0485  8   56.2877 -96.5753    
## rock-dwelling    0.2794  -0.0564 0.101   
## 
## (R thinks it has found the ML solution for model 4.)
\end{verbatim}

\hypertarget{variable-rate-brownian-motion}{%
\subsection{Variable rate Brownian motion}\label{variable-rate-brownian-motion}}

Lastly, I recently added a function to \emph{phytools} that permits us to fit a variable-rate Brownian evolution model using penalized likelihood (Revell 2021). Under this model we assume that our trait evolves via a standard Brownian motion process -- but that the rate of evolution (\(\sigma^{2}\)) itself also changes through time and among the clades of our tree\ldots{} via a process of geometric Brownian motion. As one might expect for a penalized likelihood method, when we go ahead and fit this model to data, the degree to which the evolutionary rate is permitted to vary from edge to edge in the tree is controlled by our \(\lambda\) penalty or ``smoothing'' coefficient (Revell 2021).

This method has already been used to, for example, investigate rate heterogeneity differences in body size evolution between cetaceans and plesiosaurs (Sander et al. 2021). Here, I'll apply it to the analysis of skull size evolution in a phylogenetic tree of primates. My data for this example (now packaged with \emph{phytools}) come from a book chapter by Kirk and Kay (2004).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(primate.tree)}
\FunctionTok{data}\NormalTok{(primate.data)}
\end{Highlighting}
\end{Shaded}

Our data frame, \texttt{primate.data}, contains a number of different variables. Let's pull out just one of these, \texttt{Skull\_length}, and (as we do) convert it to a logarithmic scale.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primate.lnSkull}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}
  \FunctionTok{log}\NormalTok{(primate.data}\SpecialCharTok{$}\NormalTok{Skull\_length),}
  \FunctionTok{rownames}\NormalTok{(primate.data))}
\FunctionTok{head}\NormalTok{(primate.lnSkull)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Allenopithecus_nigroviridis           Alouatta_palliata 
##                    4.590057                    4.698661 
##          Alouatta_seniculus           Aotus_trivirgatus 
##                    4.682131                    4.102643 
##           Arctocebus_aureus     Arctocebus_calabarensis 
##                    3.901973                    3.985273
\end{verbatim}

With just this input data vector and our tree, we're already ready to run our penalized likelihood analysis. Invariably, however, penalized likelihood requires the user to specify a smoothing parameter -- normally denominated \(\lambda\). \(\lambda\) determines the weight that's assigned to the penalty term of the fitted model, in our case a measure of how much (or how little) the evolutionary rate evolves from edge to edge in the tree (Revell 2021). A large value of \(\lambda\) will penalize high rate variation between edges and thus cause us to fit a model with relatively low rate heterogeneity across the tree. Smaller values of \(\lambda\), on the other hand, should allow the rate of evolution to vary with relatively little smoothing cost.

A number of approaches, such as cross-validation (e.g., Efron and Gong 1983), have been recommended to help us identify suitable values of \(\lambda\) for our data and question -- however, I would minimally suggest testing multiple values of \(\lambda\) and comparing the results! Let's do exactly that for our analysis of primate skull length: first using \(\lambda\) = 1.0, and then swapping it for a much smaller \(\lambda\) = 0.1 and much larger \(\lambda\) = 10. This will allow us to pretty quickly see how these different values of our smoothing parameter affect our findings, and thus how sensitive any inference we draw might be to the specific value of \(\lambda\) we assigned!

Before continuing, however, we might get a better sense of our data by creating a simple projection of our phenotypic trait (log skull length) onto the tree. In this case, I'll use two different plotting methods.

First, I'll use the \emph{phytools} function \texttt{edge.widthMap} which sizes the thickness of our plotted branches in proportion to the observed or reconstructed trait values. (This is one of my favorite \emph{phytools} functions, but, compared to \texttt{contMap}, it's been used very little in published literature!) We can see the result in Figure \ref{fig:primate-edgewidth}a.

In addition to this visualization, I'll also undertake a simple project our phylogeny into the trait space. This is done using a popular \emph{phytools} plotting method called \texttt{phenogram} (Evans et al. 2009; Revell 2013). In the typical style of this kind of plot, our phylogeny is graphed in a space defined by time since the root of the tree (on our horizontal axis), and the observed or reconstructed values of our phenotypic trait (on the vertical, Revell 2013). The result of this projection is shown in Figure \ref{fig:primate-edgewidth}b.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{primate.widthMap}\OtherTok{\textless{}{-}}\FunctionTok{edge.widthMap}\NormalTok{(primate.tree,}
\NormalTok{  primate.lnSkull)}
\FunctionTok{plot}\NormalTok{(primate.widthMap,}\AttributeTok{color=}\FunctionTok{palette}\NormalTok{()[}\DecValTok{2}\NormalTok{],}
  \AttributeTok{legend=}\StringTok{"log(skull length)"}\NormalTok{,}\AttributeTok{border=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{fsize=}\FloatTok{0.4}\NormalTok{,}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{4.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"a)"}\NormalTok{,}\AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{line=}\DecValTok{0}\NormalTok{,}\AttributeTok{cex=}\FloatTok{1.4}\NormalTok{)}
\FunctionTok{phenogram}\NormalTok{(primate.tree,primate.lnSkull,}\AttributeTok{fsize=}\FloatTok{0.4}\NormalTok{,}\AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}
  \AttributeTok{spread.cost=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{),}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{4.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{),}\AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.8}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"log(skull length)"}\NormalTok{)}
\FunctionTok{mtext}\NormalTok{(}\StringTok{"b)"}\NormalTok{,}\AttributeTok{adj=}\DecValTok{0}\NormalTok{,}\AttributeTok{line=}\DecValTok{0}\NormalTok{,}\AttributeTok{cex=}\FloatTok{1.4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/primate-edgewidth-1} \caption{a) Primate skull lengths (on a log scale) projected onto the edges and nodes of the phylogeny. The width of each edge of the tree is proportional to the observed or reconstructed value of the trait. See main text for more details. b) A projection of the phylogeny of a) into a space defined by time since the root (on the horizontal axis) and log skull length.}\label{fig:primate-edgewidth}
\end{figure}

Visual inspection of Figure \ref{fig:primate-edgewidth} may give us a preliminary sense of where in our tree our penalized likelihood method could end up showing the rate of primate skull length evolution to vary the most -- and the least.

The function we'll use to fit our rate-variable model, \texttt{multirateBM}, performs a computationally intensive optimization. Setting the optional argument \texttt{parallel=TRUE} will help distribute this burden across multiple processors of our computer, if possible.

Let's start with \(\lambda\) = 1.0.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primate.mBM\_1}\OtherTok{\textless{}{-}}\FunctionTok{multirateBM}\NormalTok{(primate.tree,}
\NormalTok{  primate.lnSkull,}\AttributeTok{lamba=}\DecValTok{1}\NormalTok{,}\AttributeTok{parallel=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Beginning optimization....
## Using socket cluster with 16 nodes on host 'localhost'.
## Optimization iteration 1. Using "L-BFGS-B" (parallel) 
## optimization method.
## Best (penalized) log-likelihood so far: -267.108 
## Done optimization.
\end{verbatim}

Now we can do the same with \(\lambda\) = 0.1 and 10. This time I'll turn off printing by updating the optional argument to \texttt{quiet=TRUE}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{primate.mBM\_0}\FloatTok{.1}\OtherTok{\textless{}{-}}\FunctionTok{multirateBM}\NormalTok{(primate.tree,}
\NormalTok{  primate.lnSkull,}\AttributeTok{lambda=}\FloatTok{0.1}\NormalTok{,}\AttributeTok{parallel=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{primate.mBM\_10}\OtherTok{\textless{}{-}}\FunctionTok{multirateBM}\NormalTok{(primate.tree,}
\NormalTok{  primate.lnSkull,}\AttributeTok{lambda=}\DecValTok{10}\NormalTok{,}\AttributeTok{parallel=}\ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

(Readers should take special care to note that the specific values of the penalized log likelihoods are not comparable between analyses with different values of the penalty coefficient, \(\lambda\)!)

Finally, let's visualize the differences and similarities between each of our three fitted models.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(primate.mBM\_1,}\AttributeTok{ftype=}\StringTok{"off"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}
  \AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"a) "}\NormalTok{,lambda,}\StringTok{" = 1"}\NormalTok{)),}
  \AttributeTok{adj=}\FloatTok{0.1}\NormalTok{,}\AttributeTok{line=}\FloatTok{0.5}\NormalTok{,}\AttributeTok{cex=}\FloatTok{1.1}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(primate.mBM\_0}\FloatTok{.1}\NormalTok{,}\AttributeTok{ftype=}\StringTok{"off"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}
  \AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"b) "}\NormalTok{,lambda,}\StringTok{" = 0.1"}\NormalTok{)),}
  \AttributeTok{adj=}\FloatTok{0.1}\NormalTok{,}\AttributeTok{line=}\FloatTok{0.5}\NormalTok{,}\AttributeTok{cex=}\FloatTok{1.1}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(primate.mBM\_10,}\AttributeTok{ftype=}\StringTok{"off"}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}
  \AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{,}\FloatTok{0.1}\NormalTok{))}
\FunctionTok{mtext}\NormalTok{(}\FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"c) "}\NormalTok{,lambda,}\StringTok{" = 10"}\NormalTok{)),}
  \AttributeTok{adj=}\FloatTok{0.1}\NormalTok{,}\AttributeTok{line=}\FloatTok{0.5}\NormalTok{,}\AttributeTok{cex=}\FloatTok{1.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/multirateBM-1} \caption{Estimated rates of log(skull length) evolution in primates under a variable-rate Brownian evolution model for different values of the smoothing parameter, $\lambda$. Increasing values of $\lambda$ should correspond to less variation in the rate of evolution across the tree. See main text for additional details.}\label{fig:multirateBM}
\end{figure}

We can see from the plot of Figure \ref{fig:multirateBM} that even though the specific range of rate variation depends strongly on our specified values of \(\lambda\), the pattern from clade to clade on the tree is relatively robust. This should give us some measure of confidence that the our inferred rate heterogeneity may be a product of real variability in the evolutionary rate for our character on the phylogeny!

\hypertarget{diversification}{%
\section{Diversification}\label{diversification}}

In addition to the methods that we've seen so far, \emph{phytools} also contains a handful of different techniques for investigating diversification on reconstructed phylogenies. Diversification has never been the primary focus of the \emph{phytools} R package (to that end, I'd recommend the powerful \emph{diversitree} package, FitzJohn 2012), but these methods are popular, and the \emph{phytools} implementations can be relatively easy to use.

\emph{phytools} contains methods to compute and visualize the accumulation of lineages through time, including with extinction (\texttt{ltt}), to calculate and test the \(\gamma\) statistic (\texttt{gammatest}, \texttt{mccr}, Pybus and Harvey 2000), to fit pure-birth and birth-death models, including with random missing taxa (\texttt{fit.yule} and \texttt{fit.bd}, Nee et al. 1994; Stadler 2013), to compare diversification rates between trees (\texttt{ratebytree}, Revell 2018), and to simulate stochastic trees under various conditions (\texttt{pbtree}).

\hypertarget{lineage-through-time-plots}{%
\subsection{Lineage through time plots}\label{lineage-through-time-plots}}

One of the most rudimentary phylogenetic methods for studying diversification is to simply graph the accumulation of new lineages in our reconstructed phylogeny over time since the global root of the tree. This visualization method is called a lineage-through-time plot.

One of the great appeals of this visualization is that if we graph the number of lineages through time in a fully-sampled pure-birth (that is, constant-rate speciation, but no extinction) phylogenetic tree, the accumulation curve should be exponential -- or exactly linear on a semi-logarithmic scale. This means that the lineage-through-time plot gives us a handy tool that we can use to compare the real lineage accumulation in our reconstructed tree to this simple, neutral expectation (Pybus and Harvey 2000; Revell and Harmon 2022).

To see how the number of lineages through time are calculated and graphed using \emph{phytools}, let's load a phylogenetic tree of lizards from the diverse South American family Liolaemidae. This phylogeny is packaged with \emph{phytools} but was published by Esquerré et al. (2019).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(liolaemid.tree)}
\FunctionTok{print}\NormalTok{(liolaemid.tree,}\AttributeTok{printlen=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Phylogenetic tree with 257 tips and 256 internal nodes.
## 
## Tip labels:
##   Liolaemus_abaucan, Liolaemus_koslowskyi, ...
## 
## Rooted; includes branch lengths.
\end{verbatim}

We're going to create our lineage-through-time graph with \emph{phytools} over two steps.

First, we'll use the \emph{phytools} function \texttt{ltt} to compute an object of class \texttt{"ltt"} containing our tree and a count of the number of lineages through time from the root of the tree to the tips.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{liolaemid.ltt}\OtherTok{\textless{}{-}}\FunctionTok{ltt}\NormalTok{(liolaemid.tree,}\AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{)}
\NormalTok{liolaemid.ltt}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Object of class "ltt" containing:
## 
## (1) A phylogenetic tree with 257 tips and 256 internal
##     nodes.
## 
## (2) Vectors containing the number of lineages (ltt) and
##     branching times (times) on the tree.
## 
## (3) A value for Pybus & Harvey's "gamma" statistic of
##     gamma = 1.8129, p-value = 0.0698.
\end{verbatim}

From the print-out we see that in addition to the tree and the lineages through time, our object also contains a value of (and a P-value for) Pybus and Harvey's (2000) \(\gamma\) statistic.

\(\gamma\) is a numerical value used to describe the general shape of the lineage through time curve. If the curve is straight (on a semi-log scale), then \(\gamma\) should have a value close to zero. This is what we expect under a pure-birth (speciation only) diversification process. On the other hand, significantly positive or significantly negative \(\gamma\) mean that the lineage through time graph curves upward or downward towards the present day (Pybus and Harvey 2000). This could mean that the rate of diversification has changed over time, but it could also be due to past extinction or incomplete taxon sampling (Revell and Harmon 2022).

We can see that for our liolaemid lizards, \(\gamma\) is slightly \emph{positive}, though not significantly so.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{5.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{1.1}\NormalTok{,}\FloatTok{2.1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(liolaemid.ltt,}\AttributeTok{show.tree=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{2}\NormalTok{,}
  \AttributeTok{log.lineages=}\ConstantTok{FALSE}\NormalTok{,}\AttributeTok{log=}\StringTok{"y"}\NormalTok{,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}
  \AttributeTok{cex.axis=}\FloatTok{0.8}\NormalTok{,}\AttributeTok{cex.lab=}\FloatTok{0.9}\NormalTok{,}\AttributeTok{transparency=}\FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/liol-ltt-1} \caption{Lineage through time plot for phylogeny of lizards from the South American family Liolaemidae. See main text for more details.}\label{fig:liol-ltt}
\end{figure}

In general, accounting for incomplete taxon sampling in the measurement of the \(\gamma\) statistic is important because missing taxa will tend to pull our lineage-through-time curve downwards as we approach the tips of the tree -- in other words, towards more negative values of \(\gamma\).

Fortunately, there's a simple way to address this bias. If we know the true species richness of our clade of interest, we can simply simulate trees that match this richness under pure-birth, randomly prune taxa to the level of ``missingness'' in our reconstructed tree, and then use the distribution of \(\gamma\) values across this set of simulated (and then randomly pruned) trees as our null distribution for hypothesis testing! This exact procedure is called the ``Monte Carlo constant rates'' (or MCCR, Pybus and Harvey 2000) test and is implemented in the \emph{phytools} function \texttt{mccr}.

Of course, since the MCCR test accounts for randomly missing taxa from our tree, we must know or hypothesize a true species richness of our clade. In this instance, we're not too preoccupied about the precise value for Liolaemidae, but the \emph{Reptile Database} puts the species richness of this diverse South American family at 340. For illustrative purposes only, let's just go with this number!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{liolaemid.mccr}\OtherTok{\textless{}{-}}\FunctionTok{mccr}\NormalTok{(liolaemid.ltt,}
  \AttributeTok{rho=}\FunctionTok{Ntip}\NormalTok{(liolaemid.tree)}\SpecialCharTok{/}\DecValTok{340}\NormalTok{,}\AttributeTok{nsim=}\DecValTok{1000}\NormalTok{)}
\NormalTok{liolaemid.mccr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Object of class "mccr" consisting of:
## 
## (1) A value for Pybus & Harvey's "gamma" statistic of 
##     gamma = 1.8129.
## 
## (2) A two-tailed p-value from the MCCR test of 0.002.
## 
## (3) A simulated null-distribution of gamma from 1000
##     simulations.
\end{verbatim}

This tells us that, having accounted for missing taxa, our observed value of \(\gamma\) becomes highly significantly different from that expected under pure-birth. We can plot our results to see what I mean.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{5.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\FloatTok{2.1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(liolaemid.mccr,}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.lab=}\FloatTok{0.8}\NormalTok{,}
  \AttributeTok{cex.axis=}\FloatTok{0.7}\NormalTok{,}\AttributeTok{main=}\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/liol-mccr-1} \caption{Lineage through time plot for phylogeny of lizards from the South American family Liolaemidae.}\label{fig:liol-mccr}
\end{figure}

Figure \ref{fig:liol-mccr} shows that the measured value of \(\gamma\) by this test is strongly significantly positive -- in other words (accounting for missing taxa), much larger than expected by random chance under a constant-rate pure birth speciation process!

\hypertarget{modeling-speciation-and-extinction}{%
\subsection{Modeling speciation and extinction}\label{modeling-speciation-and-extinction}}

In addition to these analysis, \emph{phytools} can also fit simple speciation and extinction models following Nee et al. (1994; Stadler 2013; Harmon 2019). This is done primarily using the function \texttt{fit.bd}, which also allows us to take into account an incomplete taxonomic sampling fraction (Stadler 2013).

Just as with \(\gamma\), incomplete sampling has the potentially to substantially distort our estimated rates of speciation (normally given as \(\lambda\) -- a different \(\lambda\) from before!) and extinction (\(\mu\)). In this case, ignoring (or underestimating) the missing lineages in our tree will tend to cause us to underestimate the rate of extinction, as nearly all of the information we have about extinction comes from the most recent parts of our phylogeny! (See Harmon 2019; Revell and Harmon 2022 for more details.)

Fitting a birth-death model using \emph{phytools} is very easy. We'll pass our liolaemid tree to the \texttt{fit.bd} function, and the only additional argument to be assigned is \texttt{rho} (for \(\rho\)), the sampling fraction, which we'll set to have a value equal to the number of tips in our tree divided by the quantity (340, see above) that we hypothesize represents the true species richness of Liolaemidae.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{liolaemid.bd}\OtherTok{\textless{}{-}}\FunctionTok{fit.bd}\NormalTok{(liolaemid.tree,}
  \AttributeTok{rho=}\FunctionTok{Ntip}\NormalTok{(liolaemid.tree)}\SpecialCharTok{/}\DecValTok{340}\NormalTok{)}
\NormalTok{liolaemid.bd}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Fitted birth-death model:
## 
## ML(b/lambda) = 0.351 
## ML(d/mu) = 0.1771 
## log(L) = 526.451 
## 
## Assumed sampling fraction (rho) = 0.7559 
## 
## R thinks it has converged.
\end{verbatim}

Other R packages (such as the aforementioned \emph{diversitree}) might allow us to compare our fitted birth-death model to a range of other hypotheses about diversification, such as that the speciation and extinction rates change through time or as a function of our phenotypic traits (e.g., Maddison et al. 2007; FitzJohn 2010; Morlon et al. 2010; Revell and Harmon 2022). In \emph{phytools} we can compare our fitted birth-death model to only one alternative model: the simpler, pure-birth model -- also called a `Yule' model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{liolaemid.yule}\OtherTok{\textless{}{-}}\FunctionTok{fit.yule}\NormalTok{(liolaemid.tree,}
  \AttributeTok{rho=}\FunctionTok{Ntip}\NormalTok{(liolaemid.tree)}\SpecialCharTok{/}\DecValTok{340}\NormalTok{)}
\NormalTok{liolaemid.yule}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Fitted Yule model:
## 
## ML(b/lambda) = 0.2499 
## log(L) = 521.2295 
## 
## Assumed sampling fraction (rho) = 0.7559 
## 
## R thinks it has converged.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(liolaemid.yule,liolaemid.bd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  log(L) d.f.       AIC    weight
## liolaemid.yule 521.2295    1 -1040.459 0.0144644
## liolaemid.bd   526.4510    2 -1048.902 0.9855356
\end{verbatim}

This result tells us that, in the context of the two very simple models that we've fit to our reconstructed tree, a two-parameter birth-death (speciation and extinction) model is much better supported than our simpler Yule model!

Lastly, the \emph{phytools} function \texttt{fit.bd} exports a likelihood function as part of the fitted model object. This, in turn, makes it very straightforward for \emph{phytools} users to (for example) compute and graph the likelihood surface. Here, I'll illustrate this using the base R graphics function \texttt{persp}. (But R and contributed R packages contain lots of even fancier 3D plotting methods that readers might be more interested in trying!)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ngrid}\OtherTok{\textless{}{-}}\DecValTok{40}
\NormalTok{b}\OtherTok{\textless{}{-}}\FunctionTok{seq}\NormalTok{(}\FloatTok{0.25}\NormalTok{,}\FloatTok{0.45}\NormalTok{,}\AttributeTok{length.out=}\NormalTok{ngrid)}
\NormalTok{d}\OtherTok{\textless{}{-}}\FunctionTok{seq}\NormalTok{(}\FloatTok{0.10}\NormalTok{,}\FloatTok{0.25}\NormalTok{,}\AttributeTok{length.out=}\NormalTok{ngrid)}
\NormalTok{logL}\OtherTok{\textless{}{-}}\FunctionTok{matrix}\NormalTok{(}\ConstantTok{NA}\NormalTok{,ngrid,ngrid)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{ngrid) }\ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{ngrid)}
\NormalTok{  logL[i,j]}\OtherTok{\textless{}{-}}\NormalTok{liolaemid.bd}\SpecialCharTok{$}\FunctionTok{lik}\NormalTok{(}\FunctionTok{c}\NormalTok{(b[i],d[j]))}
\NormalTok{logL[}\FunctionTok{is.nan}\NormalTok{(logL)]}\OtherTok{\textless{}{-}}\FunctionTok{min}\NormalTok{(logL[}\SpecialCharTok{!}\FunctionTok{is.nan}\NormalTok{(logL)])}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{rep}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\FunctionTok{persp}\NormalTok{(b,d,}\FunctionTok{exp}\NormalTok{(logL),}\AttributeTok{shade=}\FloatTok{0.3}\NormalTok{,}
  \AttributeTok{phi=}\DecValTok{45}\NormalTok{,}\AttributeTok{theta=}\DecValTok{20}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"speciation rate"}\NormalTok{,}
  \AttributeTok{ylab=}\StringTok{"extinction rate"}\NormalTok{,}
  \AttributeTok{zlab=}\StringTok{"likelihood"}\NormalTok{,}
  \AttributeTok{border=}\FunctionTok{palette}\NormalTok{()[}\DecValTok{4}\NormalTok{],}\AttributeTok{expand=}\FloatTok{0.3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/liol-bd-3d-1} \caption{Visualization of the likelihood surface for speciation and extinction rates estimated for a phylogenetic tree of Liolaemidae. The ridge of values with similar likelihoods is typical of this class of model. See main text for more details.}\label{fig:liol-bd-3d}
\end{figure}

(Some astute readers will notice the line \texttt{logL{[}is.nan(logL){]}} \texttt{\textless{}-} \texttt{min(...)} (etc.) in my script of above. This is because during our grid evaluation of the likelihood function, sometimes the function was being evaluated in parameter space where the likelihood is not defined. To account for this I set all parts of the likelihood surface that could not be computed to the numerical minimum of the graph!)

Figure \ref{fig:liol-bd-3d} shows the very strong \emph{ridge} in the likelihood surface (from low \(\lambda\) and low \(\mu\), to high \(\lambda\) and high \(\mu\)) that almost invariably tends to characterize the likelihood surfaces of birth-death models.

\hypertarget{visualization}{%
\section{Visualization}\label{visualization}}

After phylogenetic comparative analysis, \emph{phytools} is perhaps best known for its phylogeny visualization methods.

We've seen a number of these approaches already deployed throughout this article. For example, in Figures \ref{fig:simmap-trees}, \ref{fig:posterior-probs}, \ref{fig:num-changes}, \ref{fig:densityMap}, \ref{fig:anc-fitpolyMk}, and \ref{fig:trop-tree} I illustrated custom \emph{phytools} plotting methods for stochastic character mapping and the analysis of stochastically mapped trees. Likewise, in Figures \ref{fig:structure-polyMk} and \ref{fig:ordered-ard-fitpolyMk} I demonstrated \emph{phytools} plotting methods for fitted discrete character evolution models. In Figures \ref{fig:phylosig}, \ref{fig:cordylid-ace}, \ref{fig:primate-edgewidth}, and \ref{fig:multirateBM} I showed a variety of custom methods for visualizing continuous trait evolution. Finally, in Figures \ref{fig:ltt-fitpolyMk}, \ref{fig:liol-ltt}, and \ref{fig:liol-mccr} I illustrated several different approaches for graphing diversification or the results from an analysis of diversification on the tree. This is a sparse sample of the variety of plotting methods for phylogenies, phylogenetic comparative data, and the results of phylogenetic analysis that are implemented in the \emph{phytools} package.

In this final section, I'll illustrate just a few more popular plotting methods of the package that we haven't already seen in prior bits of the present article.

\hypertarget{co-phylogenetic-plotting}{%
\subsection{Co-phylogenetic plotting}\label{co-phylogenetic-plotting}}

Among the most popular plotting method of the \emph{phytools} package is the function \texttt{cophylo}, which creates co-phylogenetic plots (often referred to as ``tanglegrams,'' Page 1993).

The purpose of tanglegrams varies widely from study to study. Classically, for instance, tanglegrams are used to visually illustrate the topological similarity between two groups that are hypothesized to co-speciate: for instance, an animal host and its parasites, or a plant and its pollinators (e.g., Page 1993; Medina and Langmore 2016; Endara et al. 2018; Caraballo 2022).

Equally often, however, tanglegrams are put to different purposes. For instance, tanglegrams are frequently employed to show the similarity or differences between alternative phylogenetic hypotheses (e.g., Amarasinghe et al. 2021), to identify incongruence among gene trees (e.g., Stull et al. 2020), and even to compare a phylogenetic history to a non-phylogenetic cluster dendogram based on phenotypic or ecological data (e.g., Atkinson et al. 2020; Huie et al. 2021).

To illustrate the \emph{phytools} tanglegram method, I'll use a phylogenetic tree of bat species and another of their betacoronaviruses -- both based on Caraballo (2022).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(bat.tree)}
\FunctionTok{data}\NormalTok{(betaCoV.tree)}
\end{Highlighting}
\end{Shaded}

Assuming that our tip labels differ between our different trees (and they do in this instance), we need more than just two phylogenies to create a tanglegram -- we also need a table of associations linking the tip labels of one tree to those of the other! Again, based on Caraballo (2022), our association information for the two trees that we've loaded is contained in the \emph{phytools} data object \texttt{bat\_virus.data}. Let's load and review it.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(bat\_virus.data)}
\FunctionTok{head}\NormalTok{(bat\_virus.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    Bats betaCoVs
## 1    Artibeus lituratus KT717381
## 2 Artibeus planirostris MN872692
## 3 Artibeus planirostris MN872690
## 4 Artibeus planirostris MN872691
## 5 Artibeus planirostris MN872689
## 6 Artibeus planirostris MN872688
\end{verbatim}

Inspecting just the first part of this object reveals its general structure. We can see that it consists of two columns: one for each of our two trees. The elements of the first column should match the labels of our first tree, and those of the second column the labels of our second tree. There's no problem at all if one or the other column has repeating names: a host can (of course) be associated with more than one parasite, and vice versa!

Now let's run our co-phylogenetic analysis. This will create, not a plot, but a \texttt{"cophylo"} object in which the node rotation has been optimized to maximize the tip alignment of the two trees.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bat.cophylo}\OtherTok{\textless{}{-}}\FunctionTok{cophylo}\NormalTok{(bat.tree,betaCoV.tree,}
  \AttributeTok{assoc=}\NormalTok{bat\_virus.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rotating nodes to optimize matching...
## Done.
\end{verbatim}

We can print this object, as follows.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bat.cophylo}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Object of class "cophylo" containing:
## 
## (1) 2 (possibly rotated) phylogenetic trees in an object of class 
##     "multiPhylo".
## 
## (2) A table of associations between the tips of both trees.
\end{verbatim}

To plot it, we'll use the a generic \emph{phytools} \texttt{plot} method for the object class. I'll go ahead and adjust a few settings of the method to make our graph look nice -- and I'll use species-specific linking line colors so that we can more easily visualize all the different virus sequences that are associated with each bat host! (My color palette comes from the \emph{RColorBrewer} function \texttt{brewer.pal}, Neuwirth 2022.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(RColorBrewer}\SpecialCharTok{::}\FunctionTok{brewer.pal}\NormalTok{(}
  \AttributeTok{n=}\DecValTok{7}\NormalTok{,}\AttributeTok{name=}\StringTok{"Dark2"}\NormalTok{),bat.tree}\SpecialCharTok{$}\NormalTok{tip.label)}
\FunctionTok{par}\NormalTok{(}\AttributeTok{lend=}\DecValTok{3}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(bat.cophylo,}\AttributeTok{link.type=}\StringTok{"curved"}\NormalTok{,}
  \AttributeTok{fsize=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.7}\NormalTok{,}\FloatTok{0.6}\NormalTok{),}\AttributeTok{link.lwd=}\DecValTok{2}\NormalTok{,}
  \AttributeTok{link.lty=}\StringTok{"solid"}\NormalTok{,}\AttributeTok{pts=}\ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{link.col=}\FunctionTok{make.transparent}\NormalTok{(cols[}
\NormalTok{  bat\_virus.data[,}\DecValTok{1}\NormalTok{]],}\FloatTok{0.5}\NormalTok{))}
\NormalTok{pies}\OtherTok{\textless{}{-}}\FunctionTok{diag}\NormalTok{(}\DecValTok{1}\NormalTok{,}\FunctionTok{Ntip}\NormalTok{(bat.tree))}
\FunctionTok{colnames}\NormalTok{(pies)}\OtherTok{\textless{}{-}}\FunctionTok{rownames}\NormalTok{(pies)}\OtherTok{\textless{}{-}}\FunctionTok{names}\NormalTok{(cols)}
\FunctionTok{tiplabels.cophylo}\NormalTok{(}\AttributeTok{pie=}\NormalTok{pies,}
  \AttributeTok{piecol=}\NormalTok{cols[}
\NormalTok{  bat.cophylo}\SpecialCharTok{$}\NormalTok{trees[[}\DecValTok{1}\NormalTok{]]}\SpecialCharTok{$}\NormalTok{tip.label],}
  \AttributeTok{which=}\StringTok{"left"}\NormalTok{,}\AttributeTok{cex=}\FloatTok{0.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/bat-cophylo-1} \caption{Co-phylogenetic plot of bat species and their associated betacoronaviruses. Associations and GenBank accession numbers from Caraballo (2022). See main text for more details.}\label{fig:bat-cophylo}
\end{figure}

In general, our plot reveals a surprisingly strong association between the topology of the phylogenies of the bats and their viruses -- a pattern that Caraballo (2022) also reported (and that happened to contrast with what Caraballo found for alphacoronaviruses, for what it's worth).

\hypertarget{projecting-a-tree-onto-a-geographic-map}{%
\subsection{Projecting a tree onto a geographic map}\label{projecting-a-tree-onto-a-geographic-map}}

\emph{phytools} can also be used to project a phylogenetic tree onto a geographic map, a visualization technique that's been used in numerous published studies since it was added to the package (e.g., Csosz and Fisher 2016; Quach et al. 2019; Hermanson et al. 2020; Huang and Morgan 2021)

To see how this is done in R, we'll load two datasets that come with the \emph{phytools} package. The first is a phylogenetic tree (\texttt{mammal.tree}) from Garland et al. (1992). The second is a corresponding geographic dataset that I obtained (i.e., built laboriously by hand) by sampling 1-3 records at random from the online citizen science resource \emph{iNaturalist}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mammal.tree)}
\FunctionTok{data}\NormalTok{(mammal.geog)}
\end{Highlighting}
\end{Shaded}

Our data (\texttt{mammal.geog}) should come in the form of a matrix. This is important distinction to note because our plotting function allows more than one geographic record per species and requires that our taxon labels be supplied as row names. The most common ways to read data into R (for instance, using \texttt{read.table} or \texttt{read.csv}) create a data frames ,rather than a matrices -- and R data frames don't permit repeating row names!

The easiest way to resolve this issue when working with a dataset that isn't pre-loaded, might be to read our data in with species as a separate data column rather than as row names, and then use our input data to create a matrix object within R.

Let's take a look at the data matrix \texttt{mammal.geog} to understand how it's structured

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(mammal.geog,}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      lat       long
## A._alces       61.077601 -149.82472
## A._alces       45.655049  -69.65062
## A._americana   43.608278 -105.15943
## A._americana   40.739628 -104.51432
## A._buselaphus -19.960335   15.56863
## A._cervicapra  13.006147   80.24190
## A._cervicapra  14.656469   75.68250
## A._jubatus     -2.859852   34.90434
## A._melampus     1.307618   37.13768
## B._bison       44.974469 -110.70387
\end{verbatim}

We should see that it consists of species names as row names, as promised, and geographic locality points in the form of decimal latitude and longitude coordinates.

I happen to know that there are some mismatches between our input tree and data. (This is because I didn't include geographic records for all species when I was creating \texttt{mammal.geog} -- but it's a very common problem with comparative data!) To identify this discordance, I'm going to use the handy function \texttt{name.check} from the \emph{geiger} comparative methods package (Pennell et al. 2014).

\emph{geiger} is not a dependent package of \emph{phytools}, but I suspect that most readers (particularly any that have followed along all the way to this point) will already have it installed. If not, it can be downloaded and installed from CRAN in the typical fashion.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(geiger)}
\NormalTok{chk}\OtherTok{\textless{}{-}}\FunctionTok{name.check}\NormalTok{(mammal.tree,mammal.geog)}
\FunctionTok{summary}\NormalTok{(chk)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2 taxa are present in the tree but not the data:
##     G._granti,
##     V._fulva
## 
## To see complete list of mis-matched taxa, print object.
\end{verbatim}

This tells us that there are two taxa (\emph{G. granti} and \emph{V. fulva}) in our tree that are missing from our geographic data, so we can prune them out of our phylogeny using the \emph{ape} function \texttt{drop.tip}. (There's no need to load \emph{ape} -- loading \emph{phytools} took care of that.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mammal.pruned}\OtherTok{\textless{}{-}}\FunctionTok{drop.tip}\NormalTok{(mammal.tree,}
\NormalTok{  chk}\SpecialCharTok{$}\NormalTok{tree\_not\_data)}
\FunctionTok{name.check}\NormalTok{(mammal.pruned,mammal.geog)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "OK"
\end{verbatim}

Our next step will be to build the map projection that we intend to plot. This is done using the \emph{phytools} function \texttt{phylo.to.map}. In addition to combining our phylogenetic tree and map data, \texttt{phylo.to.map} also performs a series of node rotations designed to optimize the alignment of our phylogeny with the geographic coordinates of our tip data. As node rotation is arbitrary anyway, this can be helpful to facilitate a more convenient visualization.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mammal.map}\OtherTok{\textless{}{-}}\FunctionTok{phylo.to.map}\NormalTok{(mammal.pruned,}
\NormalTok{  mammal.geog,}\AttributeTok{plot=}\ConstantTok{FALSE}\NormalTok{,}\AttributeTok{quiet=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{mammal.map}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Object of class "phylo.to.map" containing:
## 
## (1) A phylogenetic tree with 47 tips and 46 internal nodes.
## 
## (2) A geographic map with range:
##      -85.19N, 83.6N
##      -180W, 180W.
## 
## (3) A table containing 72 geographic coordinates (may include
##     more than one set per species).
## 
## If optimized, tree nodes have been rotated to maximize alignment
## with the map when the tree is plotted in a downwards direction.
\end{verbatim}

Our plotting function for this object class allows us to specify different colors for the different species being plotted. Let's do that here by choosing random colors from a divergent color palette using the CRAN package \emph{randomcoloR} (Ammar 2019). (Readers lacking this package should install it from CRAN -- or they can elect to use a different palette, or none at all.)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(}
\NormalTok{  randomcoloR}\SpecialCharTok{::}\FunctionTok{distinctColorPalette}\NormalTok{(}
  \FunctionTok{Ntip}\NormalTok{(mammal.pruned)),}
\NormalTok{  mammal.pruned}\SpecialCharTok{$}\NormalTok{tip.label)}
\end{Highlighting}
\end{Shaded}

Finally, we're ready to plot our tree.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(mammal.map,}\AttributeTok{fsize=}\FloatTok{0.5}\NormalTok{,}\AttributeTok{ftype=}\StringTok{"i"}\NormalTok{,}
  \AttributeTok{colors=}\NormalTok{cols,}\AttributeTok{asp=}\FloatTok{0.9}\NormalTok{,}\AttributeTok{lwd=}\DecValTok{1}\NormalTok{,}
  \AttributeTok{cex.points=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{,}\FloatTok{0.8}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/mammal-geog-1} \caption{A phylogenetic tree of mammals projected onto a geographic map. Mammal phylogeny is from Garland et al. (1992), and the geographic coordinates were selected from citizen science records. See main text for more details.}\label{fig:mammal-geog}
\end{figure}

In this case, the lineages of our phylogeny in Figure \ref{fig:mammal-geog} have a near-global distribution. For phylogenetic trees whose terminal taxa have a narrower geographic range, including phylogeographic studies, it's possible to restrict the plotted maps to countries or regions, or even to supply a custom map (e.g., Quach et al. 2019)!

\hypertarget{projecting-trees-into-phenotypic-space}{%
\subsection{Projecting trees into phenotypic space}\label{projecting-trees-into-phenotypic-space}}

Along with projecting a phylogenetic tree onto a geographic map (as we just saw), and projecting traits onto the edges and nodes of a plotted tree, the \emph{phytools} package also contains multiple methods to project a tree into a space defined by our traits. Undoubtedly, the most popular of these are \texttt{phylomorphospace}, which projects a tree into a bivariate quantitative trait space (Sidlauskas 2008; e.g., Friedman et al. 2016; Martins et al. 2021), and \texttt{phenogram}, which projects a tree into a space defined by time since the root on the horizontal and phenotype on the vertical (typically called a ``traitgram,'' see Evans et al. 2009; e.g., Martinez et al. 2020; Chazot et al. 2021). We saw how \texttt{phenogram} works in Figure \ref{fig:primate-edgewidth}b of any earlier section of this article. Here, I'll focus on the \emph{phytools} method \texttt{phylomorphospace}.

For this example I'll use a time-calibrated phylogeny of 11 vertebrate species from the \emph{TimeTree} website (Hedges et al. 2006), and a phenotypic trait dataset of body mass (in kg) and mean litter size. (The latter dataset was generated from \emph{Wikipedia} and other sources: i.e., ``Googling it.'')

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(vertebrate.tree)}
\FunctionTok{data}\NormalTok{(vertebrate.data)}
\FunctionTok{head}\NormalTok{(vertebrate.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                           Mass Length Litter_size
## Carcharodon_carcharias 2268.00  6.100        10.0
## Carassius_auratus         0.91  0.380       200.0
## Latimeria_chalumnae      80.00  2.000        15.0
## Iguana_iguana             8.00  2.000        50.5
## Turdus_migratorius        0.28  0.094         4.0
## Homo_sapiens             80.00  1.700         1.1
\end{verbatim}

(We should see that our data frame actually has three columns -- but henceforward I'll just use the first and the third of these.)

Normally, we could pass our data frame or matrix and phylogeny directly to the \texttt{phylomorphospace} function and obtain a plot. \texttt{phylomorphospace} would then undertake to project the tree, using Maximum Likelihood reconstructed ancestral values for both traits as the positions for internal nodes. I'd prefer, however, to first reconstruct ancestral states on a log scale, back-transform my estimated values to the original space, and then use these back-transformed reconstruction as my node positions. Fortunately, \texttt{phylomorphospace} allows that!

For the first step, I'll use the \emph{phytools} ancestral state estimation function \texttt{fastAnc}. \texttt{fastAnc} computes Maximum Likelihood ancestral states for one input character vector at a time, so we just need to iterate across the two columns (of interest) in our data frame using an \texttt{apply} call as follows.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vertebrate.ace}\OtherTok{\textless{}{-}}\FunctionTok{exp}\NormalTok{(}\FunctionTok{apply}\NormalTok{(}\FunctionTok{log}\NormalTok{(}
\NormalTok{  vertebrate.data[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{)]),}\DecValTok{2}\NormalTok{,}
\NormalTok{  fastAnc,}\AttributeTok{tree=}\NormalTok{vertebrate.tree))}
\NormalTok{vertebrate.ace}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          Mass Litter_size
## 12  25.571594   15.552422
## 13  17.834793   16.114126
## 14  16.827622   14.481309
## 15   8.801275    8.791375
## 16  20.362215    1.653955
## 17  17.335294    1.442396
## 18  24.604666    1.610416
## 19 152.078728    1.737334
## 20 301.219076    1.582780
## 21   6.329908    9.613237
\end{verbatim}

This gives us a set of reconstructed values on our original (linear) scale, but in which the reconstruction was performed on a \emph{log} scale, and then back-transformed. Finally, let's create our phylomorphospace plot.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar=}\FunctionTok{c}\NormalTok{(}\FloatTok{5.1}\NormalTok{,}\FloatTok{4.1}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\FloatTok{2.1}\NormalTok{))}
\FunctionTok{phylomorphospace}\NormalTok{(vertebrate.tree,}
\NormalTok{  vertebrate.data[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{)],}
  \AttributeTok{A=}\NormalTok{vertebrate.ace,}\AttributeTok{log=}\StringTok{"xy"}\NormalTok{,}
  \AttributeTok{xlim=}\FunctionTok{c}\NormalTok{(}\FloatTok{1e{-}4}\NormalTok{,}\FloatTok{1e6}\NormalTok{),}\AttributeTok{ylim=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.5}\NormalTok{,}\DecValTok{200}\NormalTok{),}
  \AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{label=}\StringTok{"off"}\NormalTok{,}\AttributeTok{axes=}\ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{xlab=}\StringTok{"Mass (kg)"}\NormalTok{,}\AttributeTok{ylab=}\StringTok{"Litter size"}\NormalTok{,}
  \AttributeTok{node.size=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\FunctionTok{axis}\NormalTok{(}\DecValTok{1}\NormalTok{,}\AttributeTok{at=}\DecValTok{10}\SpecialCharTok{\^{}}\FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{,}\AttributeTok{by=}\DecValTok{2}\NormalTok{),}
  \AttributeTok{labels=}\FunctionTok{prettyNum}\NormalTok{(}\DecValTok{10}\SpecialCharTok{\^{}}\FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{,}\DecValTok{5}\NormalTok{,}\AttributeTok{by=}\DecValTok{2}\NormalTok{),}
  \AttributeTok{big.mark=}\StringTok{","}\NormalTok{),}\AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.6}\NormalTok{)}
\FunctionTok{axis}\NormalTok{(}\DecValTok{2}\NormalTok{,}\AttributeTok{at=}\DecValTok{10}\SpecialCharTok{\^{}}\FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{,}\AttributeTok{by=}\DecValTok{1}\NormalTok{),}
  \AttributeTok{labels=}\FunctionTok{prettyNum}\NormalTok{(}\DecValTok{10}\SpecialCharTok{\^{}}\FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{,}\AttributeTok{by=}\DecValTok{1}\NormalTok{),}
  \AttributeTok{big.mark=}\StringTok{","}\NormalTok{),}
  \AttributeTok{las=}\DecValTok{1}\NormalTok{,}\AttributeTok{cex.axis=}\FloatTok{0.7}\NormalTok{)}
\NormalTok{cols}\OtherTok{\textless{}{-}}\FunctionTok{setNames}\NormalTok{(RColorBrewer}\SpecialCharTok{::}\FunctionTok{brewer.pal}\NormalTok{(}
  \FunctionTok{nrow}\NormalTok{(vertebrate.data),}\StringTok{"Paired"}\NormalTok{),}
  \FunctionTok{rownames}\NormalTok{(vertebrate.data))}
\FunctionTok{points}\NormalTok{(vertebrate.data[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{3}\NormalTok{)],}\AttributeTok{pch=}\DecValTok{21}\NormalTok{,}
  \AttributeTok{bg=}\NormalTok{cols,}\AttributeTok{cex=}\FloatTok{1.2}\NormalTok{)}
\NormalTok{ind}\OtherTok{\textless{}{-}}\FunctionTok{order}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(vertebrate.data))}
\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{,}\FunctionTok{gsub}\NormalTok{(}\StringTok{"\_"}\NormalTok{,}\StringTok{" "}\NormalTok{,}
  \FunctionTok{rownames}\NormalTok{(vertebrate.data))[ind],}
  \AttributeTok{pch=}\DecValTok{21}\NormalTok{,}\AttributeTok{pt.cex=}\FloatTok{1.2}\NormalTok{,}\AttributeTok{pt.bg=}\NormalTok{cols[ind],}
  \AttributeTok{cex=}\FloatTok{0.6}\NormalTok{,}\AttributeTok{bty=}\StringTok{"n"}\NormalTok{,}\AttributeTok{text.font=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/vert-phylomorphospace-1} \caption{Phylomorphospace of body mass and litter size for a selection of vertebrate species. See main text for additional details.}\label{fig:vert-phylomorphospace}
\end{figure}

In this code, I chose to graph the projection without taxon labels, then add different colored points and a legend to put the label information back on the plot (sorting my labels alphabetically as I did this). As readers can probably imagine, taxon labels on a phylomorphospace plot can easily become very messy -- particularly for larger trees!

\hypertarget{plotting-phenotypic-data-at-the-tips-of-the-tree}{%
\subsection{Plotting phenotypic data at the tips of the tree}\label{plotting-phenotypic-data-at-the-tips-of-the-tree}}

In addition to projecting phylogenies into trait spaces, and plotting observed or reconstructed trait values on the tree, \emph{phytools} can also help us undertake the (at least, conceptually) simple task of visualizing comparative trait data for species at the tips of the tree.

This might be done in various ways. For instance, we could graph the values of a quantitative trait adjacent to the tip labels using a bar or box, or we might plot the presence or absence of different lineages from a habitat type next to the tips of the tree. Numerous such approaches have been developed and implemented in the \emph{phytools} package, and many of these are shown in my recent book (Revell and Harmon 2022).

Here, I'll illustrate just one such method in which a color gradient is used to visualize trait values for a set of quantitative characters at the tips of the tree. The \emph{phytools} implementation of this plotting method is called \texttt{phylo.heatmap}, and it's been used in numerous published articles (e.g., Goelen et al. 2020; Hultgren et al. 2021; Molina-Mora et al. 2021; Huang et al. 2022). For this example, we'll use a phylogenetic tree and morphological trait dataset for \emph{Anolis} lizards from (Mahler et al. 2010). To load these data, readers should run the following.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(anoletree)}
\FunctionTok{data}\NormalTok{(anole.data)}
\FunctionTok{head}\NormalTok{(anole.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 SVL      HL     HLL     FLL     LAM      TL
## ahli        4.03913 2.88266 3.96202 3.34498 2.86620 4.50400
## allogus     4.04014 2.86103 3.94018 3.33829 2.80827 4.52189
## rubribarbus 4.07847 2.89425 3.96135 3.35641 2.86751 4.56108
## imias       4.09969 2.85293 3.98565 3.41402 2.94375 4.65242
## sagrei      4.06716 2.83515 3.85786 3.24267 2.91872 4.77603
## bremeri     4.11337 2.86044 3.90039 3.30585 2.97009 4.72996
\end{verbatim}

Our trait data object, \texttt{anole.data}, is a data frame with six trait columns for various phylogenetic traits.

We could visualize our data directly; however, the effect of overall size (data column \texttt{"SVL"}) would tend to obscure any interesting patterns of residual variation and covariation in body shape among the species in our tree. As such, primarily in an effort to control for overall size, I'll first run a phylogenetic principal components analysis (Revell 2009) using the \emph{phytools} function \texttt{phyl.pca}. A phylogenetic principal components analysis (mentioned earlier with respect to the Broeckhoven et al. 2016 dataset) is similar to a regular PCA except that we account for non-independence of the information for different species in our data rotation (Revell 2009).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anole.ppca}\OtherTok{\textless{}{-}}\FunctionTok{phyl.pca}\NormalTok{(anoletree,anole.data,}
  \AttributeTok{mode=}\StringTok{"corr"}\NormalTok{)}
\NormalTok{anole.ppca}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Phylogenetic pca
## Standard deviations:
##       PC1       PC2       PC3       PC4       PC5       PC6 
## 2.2896942 0.6674345 0.4381067 0.2997973 0.1395612 0.1026573 
## Loads:
##            PC1         PC2         PC3         PC4           PC5
## SVL -0.9782776 -0.01988115  0.14487425 -0.11332244  0.0781070110
## HL  -0.9736568 -0.03879982  0.13442473 -0.15596460 -0.0852979941
## HLL -0.9711545  0.14491400  0.02151524  0.17058611 -0.0588208480
## FLL -0.9759133 -0.02087140  0.14486273  0.14149988  0.0475205990
## LAM -0.8299594 -0.50437051 -0.23796010  0.01194704  0.0004983465
## TL  -0.8679195  0.40956428 -0.27350654 -0.05871034  0.0195584629
##              PC6
## SVL -0.051442939
## HL   0.028570939
## HLL -0.053257988
## FLL  0.062386141
## LAM -0.003133966
## TL   0.018373275
\end{verbatim}

Our PC loadings show us the the first principal component dimension is strongly negatively correlated with all of the traits in our analysis. We could consider this the ``size'' axis. Principal component 2 is most strongly (negatively) correlated with the character \texttt{"LAM"}, number of adhesive toepad scales called lamellae; and most positively correlated with \texttt{"TL"}, tail length.

Let's compute the principal component scores for all of our species.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anole.pc\_scores}\OtherTok{\textless{}{-}}\FunctionTok{scores}\NormalTok{(anole.ppca)}
\FunctionTok{head}\NormalTok{(anole.pc\_scores)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    PC1       PC2         PC3       PC4         PC5
## ahli        -0.1747576 0.8697064  1.52379491 1.6029659 -0.23955421
## allogus      0.1646585 1.4017806  1.74506491 1.5358005 -0.08089546
## rubribarbus -0.4925001 1.0413268  1.45866163 1.4180850 -0.05716104
## imias       -1.1608049 0.7514380  0.75822327 1.7127381  0.35013533
## sagrei      -0.3486332 1.2632997 -0.05102313 0.7317455  0.37217463
## bremeri     -0.9714818 0.6943196  0.11689334 0.9290039  0.43486041
##                    PC6
## ahli        -0.1626049
## allogus     -0.1245855
## rubribarbus -0.1797060
## imias       -0.1340347
## sagrei      -0.1484157
## bremeri     -0.2304513
\end{verbatim}

Since the sign of each principal component is arbitrary (principal components are vectors), we'll now ``flip'' the sign of PC 1 -- so that it switches from negative size to simply ``size.''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anole.pc\_scores[,}\DecValTok{1}\NormalTok{]}\OtherTok{\textless{}{-}}\SpecialCharTok{{-}}\NormalTok{anole.pc\_scores[,}\DecValTok{1}\NormalTok{]}
\FunctionTok{head}\NormalTok{(anole.pc\_scores)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    PC1       PC2         PC3       PC4         PC5
## ahli         0.1747576 0.8697064  1.52379491 1.6029659 -0.23955421
## allogus     -0.1646585 1.4017806  1.74506491 1.5358005 -0.08089546
## rubribarbus  0.4925001 1.0413268  1.45866163 1.4180850 -0.05716104
## imias        1.1608049 0.7514380  0.75822327 1.7127381  0.35013533
## sagrei       0.3486332 1.2632997 -0.05102313 0.7317455  0.37217463
## bremeri      0.9714818 0.6943196  0.11689334 0.9290039  0.43486041
##                    PC6
## ahli        -0.1626049
## allogus     -0.1245855
## rubribarbus -0.1797060
## imias       -0.1340347
## sagrei      -0.1484157
## bremeri     -0.2304513
\end{verbatim}

Finally, let's graph our results using the \texttt{phylo.heatmap} function. Seeing as the variance in our different principal component dimensions are quite different from PC to PC, we'll standardize them to have a constant variance using \texttt{standardize=TRUE}. As we've done in other exercises of this article, we can update the default color palette of the plot using the argument \texttt{colors}. Here, I'll use the colorblind-friendly \texttt{viridis} color palette from the \emph{viridisLite} package (Garnier et al. 2022).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{phylo.heatmap}\NormalTok{(anoletree,anole.pc\_scores,}
  \AttributeTok{standardize=}\ConstantTok{TRUE}\NormalTok{,}\AttributeTok{fsize=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{,}\FloatTok{0.7}\NormalTok{,}\FloatTok{0.7}\NormalTok{),}
  \AttributeTok{pts=}\ConstantTok{FALSE}\NormalTok{,}\AttributeTok{split=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.4}\NormalTok{),}
  \AttributeTok{colors=}\NormalTok{viridisLite}\SpecialCharTok{::}\FunctionTok{viridis}\NormalTok{(}\AttributeTok{n=}\DecValTok{40}\NormalTok{,}
  \AttributeTok{direction=}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{),}\AttributeTok{mar=}\FunctionTok{rep}\NormalTok{(}\FloatTok{0.1}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{Revell.phytools-v2_peerj_files/figure-latex/anole-heatmap-1} \caption{Phylogenetic heatmap showing principal components from a phylogenetic PCA of six morphological traits of \textit{Anolis} lizards. Tree and data from Mahler et al. (2010). See main text for additional details.}\label{fig:anole-heatmap}
\end{figure}

In Figure \ref{fig:anole-heatmap} we can already begin to discern some of the interesting ecomorphological phenotypic patterns of \emph{Anolis} lizards (Losos 2009). For instance, the largest species (known as ``crown-giants''), that is, those species with the highest values of PC 1, tend to have moderate or low values for PC 2: meaning they have larger lamellae and shorter tails, controlling for their body size. By contrast some of the smallest species (on PC 1) have among the highest values for PC 2 (tail length). These are the ``grass-bush'' anoles that perch on grass and bushes near the grown, and use their long tails to control body pitch while jumping. Neat!

\hypertarget{relationship-of-phytools-to-other-packages}{%
\section{\texorpdfstring{Relationship of \emph{phytools} to other packages}{Relationship of phytools to other packages}}\label{relationship-of-phytools-to-other-packages}}

The \emph{phytools} package has grown to become (along with \emph{ape}, \emph{phangorn}, and \emph{geiger}) among the most important core packages for phylogenetic analysis in the R environment. As of the time of writing, the original publication describing \emph{phytools} (Revell, 2012) had been cited more than 6,700 times on \emph{Google Scholar} and continues to be cited over 1,000 times per year.

In many respect, however, \emph{phytools} owes its existence to a number of other packages making up the R phylogenetics ecosytem and from which it imports crtical functionality. In particular, \emph{phytools} depends on the object classes and methods of the core R phylogenetics package, \emph{ape} (Paradis et al. 2004; Popescu et al. 2012; Paradis and Schliep 2019). In addition, \emph{phytools} relies on a number of different methods from the multifunctional phylogenetic inference package, \emph{phangorn} (Schliep 2011). Finally, \emph{phytools} is designed to interact with a variety of other function R phylogenetics libraries, especially the \emph{geiger} package (Harmon et al. 2008; Pennell et al. 2014), which \emph{phytools} ``suggests'' but does not import.

Outside phylogenetics as such, \emph{phytools} also presently depends on or imports from a number of other R packages including \emph{clusterGeneration} (Qiu and Joe. 2020), \emph{coda} (Plummer et al. 2006), \emph{combinat} (Chasalow 2012), \emph{doParallel} (Corporation and Weston 2022), \emph{expm} (Maechler et al. 2023), \emph{foreach} (Microsoft and Weston 2022), \emph{maps} (Becker et al. 2022), \emph{MASS} (Venables and Ripley 2002), \emph{mnormt} (Azzalini and Genz 2022), \emph{nlme} (Pinheiro and Bates 2000; Pinheiro et al. 2022), \emph{numDeriv} (Gilbert and Varadhan 2019), \emph{optimParallel} (Gerber and Furrer 2019), \emph{plotrix} (J 2006), and \emph{scatterplot3d} (Ligges and Mächler 2003), although dependency relationships are dynamic as packages evolve and may change.

\hypertarget{conclusions}{%
\section{Conclusions}\label{conclusions}}

More than a decade has passed since the original and only article describing \emph{phytools} was published (Revell 2012). Since that time, the \emph{phytools} package has both evolved into one of the core function libraries of the R phylogenetics ecosystem, and expanded manyfold in size and scope. As such, I decided the literature reference for \emph{phytools} was sorely in need of updating. In creating one, however, I was determined to make something that could serve as more than a placeholder to capture citations of the \emph{phytools} package. I hope that what I've provided here will help guide new \emph{phytools} users towards interesting analytical tools, as well as perhaps inspire experienced \emph{phytools} and R phylogenetics researchers to generate new types of questions and data that will in turn help motivate continued development of the \emph{phytools} package into the future.

\hypertarget{software-and-data-availability}{%
\section{Software and data availability}\label{software-and-data-availability}}

The \emph{phytools} is free and open source, and can be downloaded from its CRAN (\url{https://CRAN.R-project.org/package=phytools}) or GitHub (\url{https://github.com/liamrevell/phytools}) pages.

This article was written in Rmarkdown (Xie et al. 2018, 2020; Allaire et al. 2023), and developed with the help of both \emph{bookdown} (Xie 2016, 2023) and the posit Rstudio IDE (RStudio Team 2020).

Markdown code and data files necessary to exactly reproduce the analyses of this article are available at \url{https://github.com/liamrevell/Revell.phytools-v2/}.

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-Allaire2023}{}}%
Allaire, J., Y. Xie, J. McPherson, J. Luraschi, K. Ushey, A. Atkins, H. Wickham, J. Cheng, W. Chang, and R. Iannone. 2023. \href{https://github.com/rstudio/rmarkdown}{Rmarkdown: Dynamic documents for r}.

\leavevmode\vadjust pre{\hypertarget{ref-Amarasinghe2021}{}}%
Amarasinghe, P., S. Joshi, N. Page, L. S. Wijedasa, M. Merello, H. Kathriarachchi, R. D. Stone, W. Judd, U. Kodandaramaiah, and N. Cellinese. 2021. Evolution and biogeography of memecylon. Am. J. Bot. 108:628--646. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Ammar2019}{}}%
Ammar, R. 2019. \href{https://CRAN.R-project.org/package=randomcoloR}{randomcoloR: Generate attractive random colors}.

\leavevmode\vadjust pre{\hypertarget{ref-Atkinson2020}{}}%
Atkinson, C. L., B. C. Ee, and J. M. Pfeiffer. 2020. \href{https://doi.org/10.1002/ecy.3100}{Evolutionary history drives aspects of stoichiometric niche variation and functional effects within a guild}. Ecology 101. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Azzalini2022}{}}%
Azzalini, A., and A. Genz. 2022. \href{http://azzalini.stat.unipd.it/SW/Pkg-mnormt/}{The {R} package \texttt{mnormt}: The multivariate normal and \(t\) distributions (version 2.1.1)}.

\leavevmode\vadjust pre{\hypertarget{ref-Baele2018-wc}{}}%
Baele, G., S. Dellicour, M. A. Suchard, P. Lemey, and B. Vrancken. 2018. Recent advances in computational phylodynamics. Curr. Opin. Virol. 31:24--32. Elsevier BV.

\leavevmode\vadjust pre{\hypertarget{ref-Beale2019-bx}{}}%
Beale, M. A., M. Marks, S. K. Sahi, L. C. Tantalo, A. V. Nori, P. French, S. A. Lukehart, C. M. Marra, and N. R. Thomson. 2019. Genomic epidemiology of syphilis reveals independent emergence of macrolide resistance across multiple circulating lineages. Nat. Commun. 10:3255. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Beaulieu2016-ww}{}}%
Beaulieu, J. M., and B. C. O'Meara. 2016. Detecting hidden diversification shifts in models of {Trait-Dependent} speciation and extinction. Syst. Biol. 65:583--601.

\leavevmode\vadjust pre{\hypertarget{ref-Beaulieu2013-zo}{}}%
Beaulieu, J. M., B. C. O'Meara, and M. J. Donoghue. 2013. Identifying hidden rate changes in the evolution of a binary morphological character: The evolution of plant habit in campanulid angiosperms. Syst. Biol. 62:725--737.

\leavevmode\vadjust pre{\hypertarget{ref-Becker2022}{}}%
Becker, R. A., A. R. Wilks, R. Brownrigg, T. P. Minka, and A. Deckmyn. 2022. \href{https://CRAN.R-project.org/package=maps}{Maps: Draw geographical maps}.

\leavevmode\vadjust pre{\hypertarget{ref-Bentz2018-xa}{}}%
Bentz, C., D. Dediu, A. Verkerk, and G. Jäger. 2018. The evolution of language families is shaped by the environment beyond neutral drift. Nat. Hum. Behav. 2:816--821. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Blinkhorn2021-gk}{}}%
Blinkhorn, J., and M. Grove. 2021. Explanations of variability in middle stone age stone tool assemblage composition and raw material use in eastern africa. Archaeol. Anthropol. Sci. 13. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Blomberg2003-as}{}}%
Blomberg, S. P., T. Garland Jr, and A. R. Ives. 2003. Testing for phylogenetic signal in comparative data: Behavioral traits are more labile. Evolution 57:717--745.

\leavevmode\vadjust pre{\hypertarget{ref-Broeckhoven2016}{}}%
Broeckhoven, C., G. Diedericks, C. Hui, B. G. Makhubo, and P. le Fras N. Mouton. 2016. \href{https://doi.org/10.1111/evo.13062}{Enemy at the gates: Rapid defensive trait diversification in an adaptive radiation of lizards}. Evolution 70:2647--2656. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Bushman2019-fs}{}}%
Bushman, F. D., K. McCormick, and S. Sherrill-Mix. 2019. Virus structures constrain transmission modes. Nat. Microbiol. 4:1778--1780. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Butler2004-av}{}}%
Butler, M. A., and A. A. King. 2004. Phylogenetic comparative analysis: A modeling approach for adaptive evolution. Am. Nat. 164:683--695.

\leavevmode\vadjust pre{\hypertarget{ref-Caraballo2022-rd}{}}%
Caraballo, D. A. 2022. Cross-species transmission of bat coronaviruses in the americas: Contrasting patterns between alphacoronavirus and betacoronavirus. Microbiol. Spectr. 10:e0141122. American Society for Microbiology.

\leavevmode\vadjust pre{\hypertarget{ref-Chasalow2012}{}}%
Chasalow, S. 2012. \href{https://CRAN.R-project.org/package=combinat}{Combinat: Combinatorics utilities}.

\leavevmode\vadjust pre{\hypertarget{ref-Chazot2021-ey}{}}%
Chazot, N., P. Blandin, V. Debat, M. Elias, and F. L. Condamine. 2021. Punctuational ecological changes rather than global factors drive species diversification and the evolution of wing phenotypes in morpho butterflies. J. Evol. Biol. 34:1592--1607. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Collar2014-sw}{}}%
Collar, D. C., P. C. Wainwright, M. E. Alfaro, L. J. Revell, and R. S. Mehta. 2014. Biting disrupts integration to spur skull evolution in eels. Nature. nature.com.

\leavevmode\vadjust pre{\hypertarget{ref-Compton2023-nc}{}}%
Compton, Z., V. Harris, W. Mellon, S. Rupp, D. Mallo, S. E. Kapsetaki, M. Wilmot, R. Kennington, K. Noble, C. Baciu, L. Ramirez, A. Peraza, B. Martins, S. Sudhakar, S. Aksoy, G. Furukawa, O. Vincze, M. Giraudeau, E. G. Duke, S. Spiro, E. Flach, H. Davidson, A. Zehnder, T. A. Graham, B. Troan, T. M. Harrison, M. Tollis, J. D. Schiffman, A. Aktipis, L. M. Abegglen, C. C. Maley, and A. M. Boddy. 2023. Cancer prevalence across vertebrates. bioRxivorg.

\leavevmode\vadjust pre{\hypertarget{ref-Microsoft2022-a}{}}%
Corporation, M., and S. Weston. 2022. \href{https://CRAN.R-project.org/package=doParallel}{doParallel: Foreach parallel adaptor for the 'parallel' package}.

\leavevmode\vadjust pre{\hypertarget{ref-Csosz2016}{}}%
Csosz, S., and B. Fisher. 2016. \href{https://doi.org/10.3897/zookeys.603.8271}{Taxonomic revision of the malagasy nesomyrmex madecassus species-group using a quantitative morphometric approach}. {ZooKeys} 603:105--130. Pensoft Publishers.

\leavevmode\vadjust pre{\hypertarget{ref-Efron1983-al}{}}%
Efron, B., and G. Gong. 1983. A leisurely look at the bootstrap, the jackknife, and cross-validation. Am. Stat. 37:36--48. Informa UK Limited.

\leavevmode\vadjust pre{\hypertarget{ref-Endara2018}{}}%
Endara, M.-J., J. A. Nicholls, P. D. Coley, D. L. Forrister, G. C. Younkin, K. G. Dexter, C. A. Kidner, R. T. Pennington, G. N. Stone, and T. A. Kursar. 2018. Tracking of host defenses and phylogeny during the radiation of neotropical inga-feeding sawflies (hymenoptera; argidae). Front. Plant Sci. 9:1237. Frontiers Media SA.

\leavevmode\vadjust pre{\hypertarget{ref-Esquerre2019-ju}{}}%
Esquerré, D., J. S. Keogh, D. Demangel, M. Morando, L. J. Avila, J. W. Sites Jr, F. Ferri-Yáñez, and A. D. Leaché. 2019. Speciation across mountains: Phylogenomics, species delimitation and taxonomy of the \emph{{L}iolaemus leopardinus} clade ({S}quamata, {L}iolaemidae).

\leavevmode\vadjust pre{\hypertarget{ref-Etienne2012-gk}{}}%
Etienne, R. S., and B. Haegeman. 2012. A conceptual and statistical framework for adaptive radiations with a key role for diversity dependence. Am. Nat. 180:E75--89.

\leavevmode\vadjust pre{\hypertarget{ref-Evans2009-gk}{}}%
Evans, M. E. K., S. A. Smith, R. S. Flynn, and M. J. Donoghue. 2009. Climate, niche evolution, and diversification of the {{``Bird-Cage''}} evening primroses ({O}enothera, sections {A}nogra and {K}leinia). Am. Nat. 173:225--240. The University of Chicago Press.

\leavevmode\vadjust pre{\hypertarget{ref-Felsenstein2012-mi}{}}%
Felsenstein, J. 2012. A comparative method for both discrete and continuous characters using the threshold model. Am. Nat. 179:145--156.

\leavevmode\vadjust pre{\hypertarget{ref-Felsenstein2002}{}}%
Felsenstein, J. 2002. Graphical methods for visualizing comparative data on phylogenies. Pp. 27--44 \emph{in} N. MacLeod and P. Forey, eds. Morphology, shape and phylogeny. Taylor; Francis, London, UK.

\leavevmode\vadjust pre{\hypertarget{ref-Felsenstein2004-ab}{}}%
Felsenstein, J. 2004. Inferring phylogenies. Sinauer associates, Sunderland, MA.

\leavevmode\vadjust pre{\hypertarget{ref-Felsenstein1985-bt}{}}%
Felsenstein, J. 1985. Phylogenies and the comparative method. Am. Nat. 125:1--15.

\leavevmode\vadjust pre{\hypertarget{ref-Felsenstein2005-am}{}}%
Felsenstein, J. 2005. Using the quantitative genetic threshold model for inferences between and within species. Philos. Trans. R. Soc. Lond. B Biol. Sci. 360:1427--1434.

\leavevmode\vadjust pre{\hypertarget{ref-FitzJohn2012-ju}{}}%
FitzJohn, R. G. 2012. Diversitree : Comparative phylogenetic analyses of diversification in {R}. Methods Ecol. Evol. 3:1084--1092. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-FitzJohn2010-cm}{}}%
FitzJohn, R. G. 2010. Quantitative traits and diversification. Syst. Biol. 59:619--633. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Freitas2020-rw}{}}%
Freitas, A. R., A. P. Tedim, C. Novais, V. F. Lanza, and L. Peixe. 2020. Comparative genomics of global optrA-carrying enterococcus faecalis uncovers a common chromosomal hotspot for optrA acquisition within a diversity of core and accessory genomes. Microb. Genom. 6. Microbiology Society.

\leavevmode\vadjust pre{\hypertarget{ref-Friedman2016-cw}{}}%
Friedman, S. T., S. A. Price, A. S. Hoey, and P. C. Wainwright. 2016. Ecomorphological convergence in planktivorous surgeonfishes. J. Evol. Biol. 29:965--978.

\leavevmode\vadjust pre{\hypertarget{ref-Garamszegi2014-dt}{}}%
Garamszegi, L. Z. 2014. Modern phylogenetic comparative methods and their application in evolutionary biology: Concepts and practice. Springer.

\leavevmode\vadjust pre{\hypertarget{ref-Garland1992-rx}{}}%
Garland, T., P. H. Harvey, and A. R. Ives. 1992. Procedures for the analysis of comparative data using phylogenetically independent contrasts. Syst. Biol. 41:18--32. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-Garnier2022}{}}%
Garnier, Simon, Ross, Noam, Rudis, Robert, Camargo, A. Pedro, Sciaini, Marco, Scherer, and Cédric. 2022. \href{https://doi.org/10.5281/zenodo.4679424}{{viridis} - colorblind-friendly color maps for r}.

\leavevmode\vadjust pre{\hypertarget{ref-Gerber2019}{}}%
Gerber, F., and R. Furrer. 2019. \href{https://doi.org/10.32614/RJ-2019-030}{optimParallel: An r package providing a parallel version of the l-BFGS-b optimization method}. The R Journal 11:352--358.

\leavevmode\vadjust pre{\hypertarget{ref-Gilbert2019}{}}%
Gilbert, P., and R. Varadhan. 2019. \href{https://CRAN.R-project.org/package=numDeriv}{numDeriv: Accurate numerical derivatives}.

\leavevmode\vadjust pre{\hypertarget{ref-Goelen2020}{}}%
Goelen, T., I. S. Sobhy, C. Vanderaa, F. Wäckers, H. Rediers, T. Wenseleers, H. Jacquemyn, and B. Lievens. 2020. Bacterial phylogeny predicts volatile organic compound composition and olfactory response of an aphid parasitoid. Oikos 129:1415--1428. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Goldberg2012-gs}{}}%
Goldberg, E. E., and B. Igić. 2012. Tempo and mode in plant breeding system evolution. Evolution 66:3701--3709. Wiley Online Library.

\leavevmode\vadjust pre{\hypertarget{ref-Halali2020}{}}%
Halali, S., E. Bergen, C. J. Breuker, P. M. Brakefield, and O. Brattström. 2020. \href{https://doi.org/10.1111/ele.13626}{Seasonal environments drive convergent evolution of a faster pace-of-life in tropical butterflies}. Ecology Letters 24:102--112. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Harmon2019-on}{}}%
Harmon, L. J. 2019. Phylogenetic comparative methods: Learning from trees. Ecoevorxiv.

\leavevmode\vadjust pre{\hypertarget{ref-Harmon2008-id}{}}%
Harmon, L. J., J. T. Weir, C. D. Brock, R. E. Glor, and W. Challenger. 2008. {GEIGER}: Investigating evolutionary radiations. Bioinformatics 24:129--131. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-Harvey1991-oj}{}}%
Harvey, P. H., and M. D. Pagel. 1991. The comparative method in evolutionary biology. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-Hedges2006-go}{}}%
Hedges, S. B., J. Dudley, and S. Kumar. 2006. {TimeTree}: A public knowledge-base of divergence times among organisms. Bioinformatics 22:2971--2972. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Hermanson2020}{}}%
Hermanson, G., F. V. Iori, S. W. Evers, M. C. Langer, and G. S. Ferreira. 2020. A small podocnemidoid (pleurodira, pelomedusoides) from the late cretaceous of brazil, and the innervation and carotid circulation of side-necked turtles. Pap. Palaeontol. 6:329--347. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Hohenlohe2008-sj}{}}%
Hohenlohe, P. A., and S. J. Arnold. 2008. {MIPoD}: A hypothesis-testing framework for microevolutionary inference from patterns of divergence. Am. Nat. 171:366--385.

\leavevmode\vadjust pre{\hypertarget{ref-Huang2021}{}}%
Huang, J.-P., and B. Morgan. 2021. Evolution of adult male horn developmental phenotypes and character displacement in xylotrupes beetles (scarabaeidae). Ecol. Evol. 11:5503--5510. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Huang2022}{}}%
Huang, X., Z. Chen, G. Yang, C. Xia, Q. Luo, X. Gao, and L. Dong. 2022. Assemblages of plasmodium and related parasites in birds with different migration statuses. Int. J. Mol. Sci. 23:10277. MDPI AG.

\leavevmode\vadjust pre{\hypertarget{ref-Huelsenbeck2003-iq}{}}%
Huelsenbeck, J. P., R. Nielsen, and J. P. Bollback. 2003. Stochastic mapping of morphological characters. Syst. Biol. 52:131--158.

\leavevmode\vadjust pre{\hypertarget{ref-Huey2019-zv}{}}%
Huey, R. B., T. Garland Jr, and M. Turelli. 2019. Revisiting a key innovation in evolutionary biology: Felsenstein's {``phylogenies and the comparative method.''} Am. Nat. 193:755--772. The University of Chicago Press Chicago, IL.

\leavevmode\vadjust pre{\hypertarget{ref-Huie2021}{}}%
Huie, J. M., I. Prates, R. C. Bell, and K. de Queiroz. 2021. Convergent patterns of adaptive radiation between island and mainland anolis lizards. Biol. J. Linn. Soc. Lond. 134:85--110. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Hultgren2021}{}}%
Hultgren, K. M., S. T. C. Chak, J. Bjelajac, and K. S. Macdonald. 2021. Correlated evolution of larval development, egg size and genome size across two genera of snapping shrimp. J. Evol. Biol. 34:1827--1839. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Lemon2006}{}}%
J, L. 2006. Plotrix: A package in the red light district of r. R-News 6:8--12.

\leavevmode\vadjust pre{\hypertarget{ref-Jezovit2020-bi}{}}%
Jezovit, J. A., R. Rooke, J. Schneider, and J. D. Levine. 2020. Behavioral and environmental contributions to drosophilid social networks. Proc. Natl. Acad. Sci. U. S. A. 117:11573--11583. Proceedings of the National Academy of Sciences.

\leavevmode\vadjust pre{\hypertarget{ref-Kirk2004-jn}{}}%
Kirk, E. C., and R. F. Kay. 2004. The evolution of high visual acuity in the anthropoidea. Pp. 539--602 \emph{in} C. F. Ross and R. F. Kay, eds. Anthropoid origins: New visions. Springer US, Boston, MA.

\leavevmode\vadjust pre{\hypertarget{ref-Lewis2001-bu}{}}%
Lewis, P. O. 2001. A likelihood approach to estimating phylogeny from discrete morphological character data. Syst. Biol. 50:913--925.

\leavevmode\vadjust pre{\hypertarget{ref-Ligges2003}{}}%
Ligges, U., and M. Mächler. 2003. \href{https://doi.org/10.18637/jss.v008.i11}{Scatterplot3d - an r package for visualizing multivariate data}. Journal of Statistical Software 8:1--20.

\leavevmode\vadjust pre{\hypertarget{ref-Losos2009-bq}{}}%
Losos, J. 2009. Lizards in an evolutionary tree: Ecology and adaptive radiation of anoles. University of California Press.

\leavevmode\vadjust pre{\hypertarget{ref-Maddison2007-mi}{}}%
Maddison, W. P., P. E. Midford, and S. P. Otto. 2007. Estimating a binary character's effect on speciation and extinction. Syst. Biol. 56:701--710. sysbio.oxfordjournals.org.

\leavevmode\vadjust pre{\hypertarget{ref-Maechler2023}{}}%
Maechler, M., C. Dutang, and V. Goulet. 2023. \href{https://CRAN.R-project.org/package=expm}{Expm: Matrix exponential, log, 'etc'}.

\leavevmode\vadjust pre{\hypertarget{ref-Mahler2010-qd}{}}%
Mahler, D. L., L. J. Revell, R. E. Glor, and J. B. Losos. 2010. Ecological opportunity and the rate of morphological evolution in the diversification of greater antillean anoles. Evolution 64:2731--2745.

\leavevmode\vadjust pre{\hypertarget{ref-Martinez2020-to}{}}%
Martinez, Q., J. Clavel, J. A. Esselstyn, A. S. Achmadi, C. Grohe, N. Pirot, and P.-H. Fabre. 2020. Convergent evolution of olfactory and thermoregulatory capacities in small amphibious mammals. Proc. Natl. Acad. Sci. U. S. A. 117:8958--8965. Proceedings of the National Academy of Sciences.

\leavevmode\vadjust pre{\hypertarget{ref-Martins2021-yo}{}}%
Martins, B. O., L. Franco-Belussi, M. S. Siqueira, C. E. Fernandes, and D. B. Provete. 2021. The evolution of red blood cell shape in fishes. J. Evol. Biol. 34:537--548. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-McLaughlin2022-wt}{}}%
McLaughlin, A., V. Montoya, R. L. Miller, G. J. Mordecai, Canadian COVID-19 Genomics Network (CanCOGen) Consortium, M. Worobey, A. F. Y. Poon, and J. B. Joy. 2022. Genomic epidemiology of the first two waves of {SARS-CoV-2} in canada. Elife 11. eLife Sciences Publications, Ltd.

\leavevmode\vadjust pre{\hypertarget{ref-Medina2016}{}}%
Medina, I., and N. E. Langmore. 2016. \href{https://doi.org/10.1111/ele.12649}{The evolution of host specialisation in avian brood parasites}. Ecology Letters 19:1110--1118. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Microsoft2022-b}{}}%
Microsoft, and S. Weston. 2022. \href{https://CRAN.R-project.org/package=foreach}{Foreach: Provides foreach looping construct}.

\leavevmode\vadjust pre{\hypertarget{ref-Mifsud2023-et}{}}%
Mifsud, J. C. O., V. A. Costa, M. E. Petrone, E. M. Marzinelli, E. C. Holmes, and E. Harvey. 2023. Transcriptome mining extends the host range of the flaviviridae to non-bilaterians. Virus Evol. 9:veac124. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-MolinaMora2021}{}}%
Molina-Mora, J. A., D. Chinchilla-Montero, R. Garcia-Batan, and F. Garcia. 2021. Genomic context of the two integrons of {ST-111} pseudomonas aeruginosa {AG1}: A {VIM-2-carrying} old-acquaintance and a novel {IMP-18-carrying} integron. Infect. Genet. Evol. 89:104740. Elsevier BV.

\leavevmode\vadjust pre{\hypertarget{ref-Morlon2010-qy}{}}%
Morlon, H., M. D. Potts, and J. B. Plotkin. 2010. Inferring the dynamics of diversification: A coalescent approach. PLoS Biol. 8.

\leavevmode\vadjust pre{\hypertarget{ref-Moura2016-as}{}}%
Moura, A., A. Criscuolo, H. Pouseele, M. M. Maury, A. Leclercq, C. Tarr, J. T. Björkman, T. Dallman, A. Reimer, V. Enouf, E. Larsonneur, H. Carleton, H. Bracq-Dieye, L. S. Katz, L. Jones, M. Touchon, M. Tourdjman, M. Walker, S. Stroika, T. Cantinelli, V. Chenal-Francisque, Z. Kucerova, E. P. C. Rocha, C. Nadon, K. Grant, E. M. Nielsen, B. Pot, P. Gerner-Smidt, M. Lecuit, and S. Brisse. 2016. Whole genome-based population biology and epidemiological surveillance of listeria monocytogenes. Nat. Microbiol. 2:16185.

\leavevmode\vadjust pre{\hypertarget{ref-Nee1994-xg}{}}%
Nee, S., R. M. May, and P. H. Harvey. 1994. The reconstructed evolutionary process. Philos. Trans. R. Soc. Lond. B Biol. Sci. 344:305--311.

\leavevmode\vadjust pre{\hypertarget{ref-Neuwirth2022}{}}%
Neuwirth, E. 2022. \href{https://CRAN.R-project.org/package=RColorBrewer}{RColorBrewer: ColorBrewer palettes}.

\leavevmode\vadjust pre{\hypertarget{ref-Nunn2011-kr}{}}%
Nunn, C. L. 2011. The comparative approach in evolutionary anthropology and biology. University of Chicago Press.

\leavevmode\vadjust pre{\hypertarget{ref-OMeara2006-cq}{}}%
O'Meara, B. C., C. Ané, M. J. Sanderson, and P. C. Wainwright. 2006. Testing for different rates of continuous trait evolution using likelihood. Evolution 60:922--933.

\leavevmode\vadjust pre{\hypertarget{ref-Page1993}{}}%
Page, R. D. M. 1993. \href{https://doi.org/10.1016/0020-7519(93)90039-2}{Parasites, phylogeny and cospeciation}. International Journal for Parasitology 23:499--506. Elsevier {BV}.

\leavevmode\vadjust pre{\hypertarget{ref-Pagel1994-ui}{}}%
Pagel, M. 1994. Detecting correlated evolution on phylogenies: A general method for the comparative analysis of discrete characters. Proc. R. Soc. Lond. B Biol. Sci. 255:37--45. The Royal Society.

\leavevmode\vadjust pre{\hypertarget{ref-Pagel1999-ic}{}}%
Pagel, M. 1999. Inferring the historical patterns of biological evolution. Nature 401:877--884.

\leavevmode\vadjust pre{\hypertarget{ref-Paradis2004-xk}{}}%
Paradis, E., J. Claude, and K. Strimmer. 2004. {APE}: Analyses of phylogenetics and evolution in {R} language. Bioinformatics 20:289--290. academic.oup.com.

\leavevmode\vadjust pre{\hypertarget{ref-Paradis2019-zp}{}}%
Paradis, E., and K. Schliep. 2019. Ape 5.0: An environment for modern phylogenetics and evolutionary analyses in {R}. Bioinformatics 35:526--528. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-Pennell2014-mo}{}}%
Pennell, M. W., J. M. Eastman, G. J. Slater, J. W. Brown, J. C. Uyeda, R. G. FitzJohn, M. E. Alfaro, and L. J. Harmon. 2014. Geiger v2. 0: An expanded suite of methods for fitting macroevolutionary models to phylogenetic trees. Bioinformatics 30:2216--2218. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-Pepke2022-wh}{}}%
Pepke, M. L., and D. T. A. Eisenberg. 2022. On the comparative biology of mammalian telomeres: Telomere length co-evolves with body mass, lifespan and cancer risk. Mol. Ecol. 31:6286--6296. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Pinheiro2000}{}}%
Pinheiro, J. C., and D. M. Bates. 2000. \href{https://doi.org/10.1007/b98882}{Mixed-effects models in s and s-PLUS}. Springer, New York.

\leavevmode\vadjust pre{\hypertarget{ref-Pinheiro2022}{}}%
Pinheiro, J., D. Bates, and R Core Team. 2022. \href{https://CRAN.R-project.org/package=nlme}{Nlme: Linear and nonlinear mixed effects models}.

\leavevmode\vadjust pre{\hypertarget{ref-Plummer2006}{}}%
Plummer, M., N. Best, K. Cowles, and K. Vines. 2006. \href{https://journal.r-project.org/archive/}{CODA: Convergence diagnosis and output analysis for MCMC}. R News 6:7--11.

\leavevmode\vadjust pre{\hypertarget{ref-Popescu2012-ui}{}}%
Popescu, A.-A., K. T. Huber, and E. Paradis. 2012. Ape 3.0: New tools for distance-based phylogenetics and evolutionary analysis in {R}. Bioinformatics 28:1536--1537. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Pozzi2022-wx}{}}%
Pozzi, L., M. Voskamp, and P. M. Kappeler. 2022. The effects of body size, activity, and phylogeny on primate sleeping ecology. Am. J. Biol. Anthropol. 179:598--608. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Pybus2000-sf}{}}%
Pybus, O. G., and P. H. Harvey. 2000. Testing macro-evolutionary models using incomplete molecular phylogenies. Proc. Biol. Sci. 267:2267--2272.

\leavevmode\vadjust pre{\hypertarget{ref-Qiu2020}{}}%
Qiu, W., and H. Joe. 2020. \href{https://CRAN.R-project.org/package=clusterGeneration}{clusterGeneration: Random cluster generation (with specified degree of separation)}.

\leavevmode\vadjust pre{\hypertarget{ref-Quach2019}{}}%
Quach, Q. N., R. G. Reynolds, and L. J. Revell. 2019. Historical allopatry and secondary contact or primary intergradation in the puerto rican crested anole, anolis cristatellus, on vieques island in the caribbean. Biol. J. Linn. Soc. Lond. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Rbase2022}{}}%
R Core Team. 2022. \href{https://www.R-project.org/}{R: A language and environment for statistical computing}. R Foundation for Statistical Computing, Vienna, Austria.

\leavevmode\vadjust pre{\hypertarget{ref-Rabosky2014-qo}{}}%
Rabosky, D. L. 2014. Automatic detection of key innovations, rate shifts, and{d}iversity-{d}ependence on phylogenetic trees. PLoS One 9:e89543. Public Library of Science.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2021}{}}%
Revell, L. J. 2021. \href{https://doi.org/10.7717/peerj.11997}{A variable-rate quantitative trait evolution model using penalized-likelihood}. {PeerJ} 9:e11997. {PeerJ}.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2014-ba}{}}%
Revell, L. J. 2014. Ancestral character estimation under the threshold model from quantitative genetics. Evolution 68:743--759.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2018-xv}{}}%
Revell, L. J. 2018. Comparing the rates of speciation and extinction between phylogenetic trees. Ecol. Evol. 8:5303--5312.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2012}{}}%
Revell, L. J. 2012. Phytools: An {R} package for phylogenetic comparative biology (and other things). Methods Ecol. Evol. 3:217--223. Wiley Online Library.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2009-vv}{}}%
Revell, L. J. 2009. Size-correction and principal components for interspecific comparative studies. Evolution 63:3258--3268. Wiley Online Library.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2013-ij}{}}%
Revell, L. J. 2013. Two new graphical methods for mapping trait evolution on phylogenies. Methods Ecol. Evol. 4:754--759. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2009-bo}{}}%
Revell, L. J., and D. C. Collar. 2009. Phylogenetic analysis of the evolutionary correlation using likelihood. Evolution 63:1090--1100.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2018-kr}{}}%
Revell, L. J., L. E. Gonzalez-Valenzuela, A. Alfonso, L. A. Castellanos-Garcia, C. E. Guarnizo, and A. J. Crawford. 2018. Comparing evolutionary rates between trees, clades and traits. Methods Ecol. Evol. 9:994--1005. Wiley Online Library.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2022-book}{}}%
Revell, L. J., and L. J. Harmon. 2022. Phylogenetic comparative methods in {R}. Princeton University Press, Princeton, NJ.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2008-vu}{}}%
Revell, L. J., L. J. Harmon, and D. C. Collar. 2008. Phylogenetic signal, evolutionary process, and rate. Syst. Biol. 57:591--601.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2008-uy}{}}%
Revell, L. J., and A. S. Harrison. 2008. {PCCA}: A program for phylogenetic canonical correlation analysis. Bioinformatics 24:1018--1020. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Revell2007-br}{}}%
Revell, L. J., M. A. Johnson, J. A. Schulte 2nd, J. J. Kolbe, and J. B. Losos. 2007. A phylogenetic test for adaptive convergence in rock-dwelling lizards. Evolution 61:2898--2912. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2012-vj}{}}%
Revell, L. J., D. L. Mahler, P. R. Peres-Neto, and B. D. Redelings. 2012. A new phylogenetic method for identifying exceptional phenotypic diversification. Evolution 66:135--146.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2015-il}{}}%
Revell, L. J., D. L. Mahler, R. G. Reynolds, and G. J. Slater. 2015. Placing cryptic, recently extinct, or hypothesized taxa into an ultrametric phylogeny using continuous character data: A case study with the lizard anolis roosevelti. Evolution 69:1027--1035. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Revell2022-tr}{}}%
Revell, L. J., K. S. Toyama, and D. L. Mahler. 2022. A simple hierarchical model for heterogeneity in the evolutionary correlation on a phylogenetic tree. PeerJ 10:e13910. PeerJ.

\leavevmode\vadjust pre{\hypertarget{ref-Rstudio2020}{}}%
RStudio Team. 2020. \href{http://www.rstudio.com/}{RStudio: Integrated development environment for r}. RStudio, PBC., Boston, MA.

\leavevmode\vadjust pre{\hypertarget{ref-Sanchez-Buso2019-nc}{}}%
Sánchez-Busó, L., D. Golparian, J. Corander, Y. H. Grad, M. Ohnishi, R. Flemming, J. Parkhill, S. D. Bentley, M. Unemo, and S. R. Harris. 2019. The impact of antimicrobials on gonococcal evolution. Nat. Microbiol. 4:1941--1950. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Sander2021-jf}{}}%
Sander, P. M., E. M. Griebeler, N. Klein, J. V. Juarbe, T. Wintrich, L. J. Revell, and L. Schmitz. 2021. Early giant reveals faster evolution of large body size in ichthyosaurs than in cetaceans. Science 374:eabf5787. American Association for the Advancement of Science (AAAS).

\leavevmode\vadjust pre{\hypertarget{ref-Schliep2011-my}{}}%
Schliep, K. P. 2011. Phangorn: Phylogenetic analysis in {R}. Bioinformatics 27:592--593.

\leavevmode\vadjust pre{\hypertarget{ref-Schluter1997-vw}{}}%
Schluter, D., T. Price, A. Ø. Mooers, and D. Ludwig. 1997. Likelihood of ancestor states in adaptive radiation. Evolution 51:1699--1711. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Sidlauskas2008-mz}{}}%
Sidlauskas, B. 2008. Continuous and arrested morphological diversification in sister clades of characiform fishes: A phylomorphospace approach. Evolution 62:3135--3156. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Stadler2013-sh}{}}%
Stadler, T. 2013. How can we improve accuracy of macroevolutionary rate estimates? Syst. Biol. 62:321--329. Oxford University Press (OUP).

\leavevmode\vadjust pre{\hypertarget{ref-Stadler2011-jy}{}}%
Stadler, T. 2011. Inferring speciation and extinction processes from extant species data. Proc. Natl. Acad. Sci. U. S. A. 108:16145--16146. National Acad Sciences.

\leavevmode\vadjust pre{\hypertarget{ref-Stull2020}{}}%
Stull, G. W., P. S. Soltis, D. E. Soltis, M. A. Gitzendanner, and S. A. Smith. 2020. \href{https://doi.org/10.1002/ajb2.1468}{Nuclear phylogenomic analyses of asterids conflict with plastome trees and support novel relationships among major lineages}. American Journal of Botany 107:790--805. Wiley.

\leavevmode\vadjust pre{\hypertarget{ref-Uyeda2014-ng}{}}%
Uyeda, J. C., and L. J. Harmon. 2014. A novel {B}ayesian method for inferring and interpreting the dynamics of adaptive landscapes from phylogenetic comparative data. Syst. Biol. 63:902--918.

\leavevmode\vadjust pre{\hypertarget{ref-Valles-Colomer2019-fk}{}}%
Valles-Colomer, M., G. Falony, Y. Darzi, E. F. Tigchelaar, J. Wang, R. Y. Tito, C. Schiweck, A. Kurilshikov, M. Joossens, C. Wijmenga, S. Claes, L. Van Oudenhove, A. Zhernakova, S. Vieira-Silva, and J. Raes. 2019. The neuroactive potential of the human gut microbiota in quality of life and depression. Nat. Microbiol. 4:623--632. Springer Science; Business Media LLC.

\leavevmode\vadjust pre{\hypertarget{ref-Van_Borm2023-db}{}}%
Van Borm, S., G. Boseret, S. Dellicour, M. Steensels, V. Roupie, F. Vandenbussche, E. Mathijs, A. Vilain, M. Driesen, M. Dispas, A. W. Delcloo, P. Lemey, I. Mertens, M. Gilbert, B. Lambrecht, and T. van den Berg. 2023. Combined phylogeographic analyses and epidemiologic contact tracing to characterize atypically pathogenic avian influenza ({H3N1}) epidemic, belgium, 2019. Emerg. Infect. Dis. 29:351--359. Centers for Disease Control; Prevention (CDC).

\leavevmode\vadjust pre{\hypertarget{ref-Venables2002}{}}%
Venables, W. N., and B. D. Ripley. 2002. \href{https://www.stats.ox.ac.uk/pub/MASS4/}{Modern applied statistics with s}. Fourth. Springer, New York.

\leavevmode\vadjust pre{\hypertarget{ref-Xie2023}{}}%
Xie, Y. 2023. \href{https://github.com/rstudio/bookdown}{Bookdown: Authoring books and technical documents with r markdown}.

\leavevmode\vadjust pre{\hypertarget{ref-Xie2016}{}}%
Xie, Y. 2016. \href{https://bookdown.org/yihui/bookdown}{Bookdown: Authoring books and technical documents with {R} markdown}. Chapman; Hall/CRC, Boca Raton, Florida.

\leavevmode\vadjust pre{\hypertarget{ref-Xie2018}{}}%
Xie, Y., J. J. Allaire, and G. Grolemund. 2018. \href{https://bookdown.org/yihui/rmarkdown}{R markdown: The definitive guide}. Chapman; Hall/CRC, Boca Raton, Florida.

\leavevmode\vadjust pre{\hypertarget{ref-Xie2022}{}}%
Xie, Y., C. Dervieux, and E. Riederer. 2020. \href{https://bookdown.org/yihui/rmarkdown-cookbook}{R markdown cookbook}. Chapman; Hall/CRC, Boca Raton, Florida.

\leavevmode\vadjust pre{\hypertarget{ref-Yang2014-uo}{}}%
Yang, Z. 2014. Molecular evolution. Oxford University Press, London, England.

\end{CSLReferences}



\end{document}
